// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "SRXDataClass.pb.h"
#import "SRXDataSchool.pb.h"
#import "SRXDataImage.pb.h"
// @@protoc_insertion_point(imports)

@class SRXDataClass;
@class SRXDataClassBuilder;
@class SRXDataClassInfo;
@class SRXDataClassInfoBuilder;
@class SRXDataClassTime;
@class SRXDataClassTimeBuilder;
@class SRXDataClassTypeEnum;
@class SRXDataClassTypeEnumBuilder;
@class SRXDataImage;
@class SRXDataImageBuilder;
@class SRXDataImageRef;
@class SRXDataImageRefBuilder;
@class SRXDataImageServerTypeEnum;
@class SRXDataImageServerTypeEnumBuilder;
@class SRXDataLocation;
@class SRXDataLocationBuilder;
@class SRXDataPersonName;
@class SRXDataPersonNameBuilder;
@class SRXDataRoleInClassTypeEnum;
@class SRXDataRoleInClassTypeEnumBuilder;
@class SRXDataSchool;
@class SRXDataSchoolBuilder;
@class SRXDataSchoolInfo;
@class SRXDataSchoolInfoBuilder;
@class SRXDataTeacher;
@class SRXDataTeacherBuilder;
@class SRXDataUser;
@class SRXDataUserBuilder;
@class SRXProtoAddImagesRequest;
@class SRXProtoAddImagesRequestBuilder;
@class SRXProtoAddImagesResponse;
@class SRXProtoAddImagesResponseBuilder;
@class SRXProtoCreateClassRequest;
@class SRXProtoCreateClassRequestBuilder;
@class SRXProtoCreateClassResponse;
@class SRXProtoCreateClassResponseBuilder;
@class SRXProtoCreateSchoolRequest;
@class SRXProtoCreateSchoolRequestBuilder;
@class SRXProtoCreateSchoolResponse;
@class SRXProtoCreateSchoolResponseBuilder;
@class SRXProtoGetImagesRequest;
@class SRXProtoGetImagesRequestBuilder;
@class SRXProtoGetImagesResponse;
@class SRXProtoGetImagesResponseBuilder;
@class SRXProtoGetOwnedSchoolRequest;
@class SRXProtoGetOwnedSchoolRequestBuilder;
@class SRXProtoGetOwnedSchoolResponse;
@class SRXProtoGetOwnedSchoolResponseBuilder;
@class SRXProtoGetProfileResponse;
@class SRXProtoGetProfileResponseBuilder;
@class SRXProtoImage;
@class SRXProtoImageBuilder;
@class SRXProtoLogInRequest;
@class SRXProtoLogInRequestBuilder;
@class SRXProtoLogInResponse;
@class SRXProtoLogInResponseBuilder;
@class SRXProtoMutableProfileRequest;
@class SRXProtoMutableProfileRequestBuilder;
@class SRXProtoMutableProfileResponse;
@class SRXProtoMutableProfileResponseBuilder;
@class SRXProtoNativeLogInMessage;
@class SRXProtoNativeLogInMessageBuilder;
@class SRXProtoReadClassRequest;
@class SRXProtoReadClassRequestBuilder;
@class SRXProtoReadClassResponse;
@class SRXProtoReadClassResponseBuilder;
@class SRXProtoReadProfileRequest;
@class SRXProtoReadProfileRequestBuilder;
@class SRXProtoSearchClassRequest;
@class SRXProtoSearchClassRequestBuilder;
@class SRXProtoSearchClassResponse;
@class SRXProtoSearchClassResponseBuilder;


typedef NS_ENUM(SInt32, SRXProtoLogInMethodEnum) {
  SRXProtoLogInMethodEnumDefault = 0,
  SRXProtoLogInMethodEnumNative = 1,
};

BOOL SRXProtoLogInMethodEnumIsValidValue(SRXProtoLogInMethodEnum value);
NSString *NSStringFromSRXProtoLogInMethodEnum(SRXProtoLogInMethodEnum value);

typedef NS_ENUM(SInt32, SRXDataRoleInClassTypeEnumSRXDataRoleInClassType) {
  SRXDataRoleInClassTypeEnumSRXDataRoleInClassTypeUnknown = 0,
  SRXDataRoleInClassTypeEnumSRXDataRoleInClassTypeOwner = 1,
  SRXDataRoleInClassTypeEnumSRXDataRoleInClassTypeStudent = 2,
};

BOOL SRXDataRoleInClassTypeEnumSRXDataRoleInClassTypeIsValidValue(SRXDataRoleInClassTypeEnumSRXDataRoleInClassType value);
NSString *NSStringFromSRXDataRoleInClassTypeEnumSRXDataRoleInClassType(SRXDataRoleInClassTypeEnumSRXDataRoleInClassType value);


@interface SrxapiRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define SRXDataUser_id @"id"
@interface SRXDataUser : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  NSString* id;
}
- (BOOL) hasId;
@property (readonly, strong) NSString* id;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXDataUserBuilder*) builder;
+ (SRXDataUserBuilder*) builder;
+ (SRXDataUserBuilder*) builderWithPrototype:(SRXDataUser*) prototype;
- (SRXDataUserBuilder*) toBuilder;

+ (SRXDataUser*) parseFromData:(NSData*) data;
+ (SRXDataUser*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataUser*) parseFromInputStream:(NSInputStream*) input;
+ (SRXDataUser*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataUser*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXDataUser*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXDataUserBuilder : PBGeneratedMessageBuilder {
@private
  SRXDataUser* resultSrxdataUser;
}

- (SRXDataUser*) defaultInstance;

- (SRXDataUserBuilder*) clear;
- (SRXDataUserBuilder*) clone;

- (SRXDataUser*) build;
- (SRXDataUser*) buildPartial;

- (SRXDataUserBuilder*) mergeFrom:(SRXDataUser*) other;
- (SRXDataUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXDataUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (SRXDataUserBuilder*) setId:(NSString*) value;
- (SRXDataUserBuilder*) clearId;
@end

#define SRXProtoCreateClassRequest_requesting_user @"requestingUser"
#define SRXProtoCreateClassRequest_class_info @"classInfo"
@interface SRXProtoCreateClassRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRequestingUser_:1;
  BOOL hasClassInfo_:1;
  SRXDataUser* requestingUser;
  SRXDataClassInfo* classInfo;
}
- (BOOL) hasRequestingUser;
- (BOOL) hasClassInfo;
@property (readonly, strong) SRXDataUser* requestingUser;
@property (readonly, strong) SRXDataClassInfo* classInfo;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoCreateClassRequestBuilder*) builder;
+ (SRXProtoCreateClassRequestBuilder*) builder;
+ (SRXProtoCreateClassRequestBuilder*) builderWithPrototype:(SRXProtoCreateClassRequest*) prototype;
- (SRXProtoCreateClassRequestBuilder*) toBuilder;

+ (SRXProtoCreateClassRequest*) parseFromData:(NSData*) data;
+ (SRXProtoCreateClassRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoCreateClassRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoCreateClassRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoCreateClassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoCreateClassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoCreateClassRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoCreateClassRequest* resultSrxprotoCreateClassRequest;
}

- (SRXProtoCreateClassRequest*) defaultInstance;

- (SRXProtoCreateClassRequestBuilder*) clear;
- (SRXProtoCreateClassRequestBuilder*) clone;

- (SRXProtoCreateClassRequest*) build;
- (SRXProtoCreateClassRequest*) buildPartial;

- (SRXProtoCreateClassRequestBuilder*) mergeFrom:(SRXProtoCreateClassRequest*) other;
- (SRXProtoCreateClassRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoCreateClassRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRequestingUser;
- (SRXDataUser*) requestingUser;
- (SRXProtoCreateClassRequestBuilder*) setRequestingUser:(SRXDataUser*) value;
- (SRXProtoCreateClassRequestBuilder*) setRequestingUserBuilder:(SRXDataUserBuilder*) builderForValue;
- (SRXProtoCreateClassRequestBuilder*) mergeRequestingUser:(SRXDataUser*) value;
- (SRXProtoCreateClassRequestBuilder*) clearRequestingUser;

- (BOOL) hasClassInfo;
- (SRXDataClassInfo*) classInfo;
- (SRXProtoCreateClassRequestBuilder*) setClassInfo:(SRXDataClassInfo*) value;
- (SRXProtoCreateClassRequestBuilder*) setClassInfoBuilder:(SRXDataClassInfoBuilder*) builderForValue;
- (SRXProtoCreateClassRequestBuilder*) mergeClassInfo:(SRXDataClassInfo*) value;
- (SRXProtoCreateClassRequestBuilder*) clearClassInfo;
@end

#define SRXProtoCreateClassResponse_class_id @"classId"
@interface SRXProtoCreateClassResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasClassId_:1;
  NSString* classId;
}
- (BOOL) hasClassId;
@property (readonly, strong) NSString* classId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoCreateClassResponseBuilder*) builder;
+ (SRXProtoCreateClassResponseBuilder*) builder;
+ (SRXProtoCreateClassResponseBuilder*) builderWithPrototype:(SRXProtoCreateClassResponse*) prototype;
- (SRXProtoCreateClassResponseBuilder*) toBuilder;

+ (SRXProtoCreateClassResponse*) parseFromData:(NSData*) data;
+ (SRXProtoCreateClassResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoCreateClassResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoCreateClassResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoCreateClassResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoCreateClassResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoCreateClassResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoCreateClassResponse* resultSrxprotoCreateClassResponse;
}

- (SRXProtoCreateClassResponse*) defaultInstance;

- (SRXProtoCreateClassResponseBuilder*) clear;
- (SRXProtoCreateClassResponseBuilder*) clone;

- (SRXProtoCreateClassResponse*) build;
- (SRXProtoCreateClassResponse*) buildPartial;

- (SRXProtoCreateClassResponseBuilder*) mergeFrom:(SRXProtoCreateClassResponse*) other;
- (SRXProtoCreateClassResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoCreateClassResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasClassId;
- (NSString*) classId;
- (SRXProtoCreateClassResponseBuilder*) setClassId:(NSString*) value;
- (SRXProtoCreateClassResponseBuilder*) clearClassId;
@end

@interface SRXDataRoleInClassTypeEnum : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXDataRoleInClassTypeEnumBuilder*) builder;
+ (SRXDataRoleInClassTypeEnumBuilder*) builder;
+ (SRXDataRoleInClassTypeEnumBuilder*) builderWithPrototype:(SRXDataRoleInClassTypeEnum*) prototype;
- (SRXDataRoleInClassTypeEnumBuilder*) toBuilder;

+ (SRXDataRoleInClassTypeEnum*) parseFromData:(NSData*) data;
+ (SRXDataRoleInClassTypeEnum*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataRoleInClassTypeEnum*) parseFromInputStream:(NSInputStream*) input;
+ (SRXDataRoleInClassTypeEnum*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataRoleInClassTypeEnum*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXDataRoleInClassTypeEnum*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXDataRoleInClassTypeEnumBuilder : PBGeneratedMessageBuilder {
@private
  SRXDataRoleInClassTypeEnum* resultSrxdataRoleInClassTypeEnum;
}

- (SRXDataRoleInClassTypeEnum*) defaultInstance;

- (SRXDataRoleInClassTypeEnumBuilder*) clear;
- (SRXDataRoleInClassTypeEnumBuilder*) clone;

- (SRXDataRoleInClassTypeEnum*) build;
- (SRXDataRoleInClassTypeEnum*) buildPartial;

- (SRXDataRoleInClassTypeEnumBuilder*) mergeFrom:(SRXDataRoleInClassTypeEnum*) other;
- (SRXDataRoleInClassTypeEnumBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXDataRoleInClassTypeEnumBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define SRXProtoReadClassRequest_requesting_user @"requestingUser"
#define SRXProtoReadClassRequest_role_in_class @"roleInClass"
@interface SRXProtoReadClassRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRequestingUser_:1;
  BOOL hasRoleInClass_:1;
  SRXDataUser* requestingUser;
  SRXDataRoleInClassTypeEnumSRXDataRoleInClassType roleInClass;
}
- (BOOL) hasRequestingUser;
- (BOOL) hasRoleInClass;
@property (readonly, strong) SRXDataUser* requestingUser;
@property (readonly) SRXDataRoleInClassTypeEnumSRXDataRoleInClassType roleInClass;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoReadClassRequestBuilder*) builder;
+ (SRXProtoReadClassRequestBuilder*) builder;
+ (SRXProtoReadClassRequestBuilder*) builderWithPrototype:(SRXProtoReadClassRequest*) prototype;
- (SRXProtoReadClassRequestBuilder*) toBuilder;

+ (SRXProtoReadClassRequest*) parseFromData:(NSData*) data;
+ (SRXProtoReadClassRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoReadClassRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoReadClassRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoReadClassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoReadClassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoReadClassRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoReadClassRequest* resultSrxprotoReadClassRequest;
}

- (SRXProtoReadClassRequest*) defaultInstance;

- (SRXProtoReadClassRequestBuilder*) clear;
- (SRXProtoReadClassRequestBuilder*) clone;

- (SRXProtoReadClassRequest*) build;
- (SRXProtoReadClassRequest*) buildPartial;

- (SRXProtoReadClassRequestBuilder*) mergeFrom:(SRXProtoReadClassRequest*) other;
- (SRXProtoReadClassRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoReadClassRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRequestingUser;
- (SRXDataUser*) requestingUser;
- (SRXProtoReadClassRequestBuilder*) setRequestingUser:(SRXDataUser*) value;
- (SRXProtoReadClassRequestBuilder*) setRequestingUserBuilder:(SRXDataUserBuilder*) builderForValue;
- (SRXProtoReadClassRequestBuilder*) mergeRequestingUser:(SRXDataUser*) value;
- (SRXProtoReadClassRequestBuilder*) clearRequestingUser;

- (BOOL) hasRoleInClass;
- (SRXDataRoleInClassTypeEnumSRXDataRoleInClassType) roleInClass;
- (SRXProtoReadClassRequestBuilder*) setRoleInClass:(SRXDataRoleInClassTypeEnumSRXDataRoleInClassType) value;
- (SRXProtoReadClassRequestBuilder*) clearRoleInClass;
@end

#define SRXProtoReadClassResponse_class_collection @"classCollection"
@interface SRXProtoReadClassResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * classCollectionArray;
}
@property (readonly, strong) NSArray * classCollection;
- (SRXDataClassInfo*)classCollectionAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoReadClassResponseBuilder*) builder;
+ (SRXProtoReadClassResponseBuilder*) builder;
+ (SRXProtoReadClassResponseBuilder*) builderWithPrototype:(SRXProtoReadClassResponse*) prototype;
- (SRXProtoReadClassResponseBuilder*) toBuilder;

+ (SRXProtoReadClassResponse*) parseFromData:(NSData*) data;
+ (SRXProtoReadClassResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoReadClassResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoReadClassResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoReadClassResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoReadClassResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoReadClassResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoReadClassResponse* resultSrxprotoReadClassResponse;
}

- (SRXProtoReadClassResponse*) defaultInstance;

- (SRXProtoReadClassResponseBuilder*) clear;
- (SRXProtoReadClassResponseBuilder*) clone;

- (SRXProtoReadClassResponse*) build;
- (SRXProtoReadClassResponse*) buildPartial;

- (SRXProtoReadClassResponseBuilder*) mergeFrom:(SRXProtoReadClassResponse*) other;
- (SRXProtoReadClassResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoReadClassResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)classCollection;
- (SRXDataClassInfo*)classCollectionAtIndex:(NSUInteger)index;
- (SRXProtoReadClassResponseBuilder *)addClassCollection:(SRXDataClassInfo*)value;
- (SRXProtoReadClassResponseBuilder *)setClassCollectionArray:(NSArray *)array;
- (SRXProtoReadClassResponseBuilder *)clearClassCollection;
@end

#define SRXProtoSearchClassRequest_latitude @"latitude"
#define SRXProtoSearchClassRequest_longtitude @"longtitude"
#define SRXProtoSearchClassRequest_radius_latitude @"radiusLatitude"
#define SRXProtoSearchClassRequest_radius_longtitude @"radiusLongtitude"
@interface SRXProtoSearchClassRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLatitude_:1;
  BOOL hasLongtitude_:1;
  BOOL hasRadiusLatitude_:1;
  BOOL hasRadiusLongtitude_:1;
  Float32 latitude;
  Float32 longtitude;
  Float32 radiusLatitude;
  Float32 radiusLongtitude;
}
- (BOOL) hasLatitude;
- (BOOL) hasLongtitude;
- (BOOL) hasRadiusLatitude;
- (BOOL) hasRadiusLongtitude;
@property (readonly) Float32 latitude;
@property (readonly) Float32 longtitude;
@property (readonly) Float32 radiusLatitude;
@property (readonly) Float32 radiusLongtitude;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoSearchClassRequestBuilder*) builder;
+ (SRXProtoSearchClassRequestBuilder*) builder;
+ (SRXProtoSearchClassRequestBuilder*) builderWithPrototype:(SRXProtoSearchClassRequest*) prototype;
- (SRXProtoSearchClassRequestBuilder*) toBuilder;

+ (SRXProtoSearchClassRequest*) parseFromData:(NSData*) data;
+ (SRXProtoSearchClassRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoSearchClassRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoSearchClassRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoSearchClassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoSearchClassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoSearchClassRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoSearchClassRequest* resultSrxprotoSearchClassRequest;
}

- (SRXProtoSearchClassRequest*) defaultInstance;

- (SRXProtoSearchClassRequestBuilder*) clear;
- (SRXProtoSearchClassRequestBuilder*) clone;

- (SRXProtoSearchClassRequest*) build;
- (SRXProtoSearchClassRequest*) buildPartial;

- (SRXProtoSearchClassRequestBuilder*) mergeFrom:(SRXProtoSearchClassRequest*) other;
- (SRXProtoSearchClassRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoSearchClassRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLatitude;
- (Float32) latitude;
- (SRXProtoSearchClassRequestBuilder*) setLatitude:(Float32) value;
- (SRXProtoSearchClassRequestBuilder*) clearLatitude;

- (BOOL) hasLongtitude;
- (Float32) longtitude;
- (SRXProtoSearchClassRequestBuilder*) setLongtitude:(Float32) value;
- (SRXProtoSearchClassRequestBuilder*) clearLongtitude;

- (BOOL) hasRadiusLatitude;
- (Float32) radiusLatitude;
- (SRXProtoSearchClassRequestBuilder*) setRadiusLatitude:(Float32) value;
- (SRXProtoSearchClassRequestBuilder*) clearRadiusLatitude;

- (BOOL) hasRadiusLongtitude;
- (Float32) radiusLongtitude;
- (SRXProtoSearchClassRequestBuilder*) setRadiusLongtitude:(Float32) value;
- (SRXProtoSearchClassRequestBuilder*) clearRadiusLongtitude;
@end

#define SRXProtoSearchClassResponse_class_collection @"classCollection"
@interface SRXProtoSearchClassResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * classCollectionArray;
}
@property (readonly, strong) NSArray * classCollection;
- (SRXDataClassInfo*)classCollectionAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoSearchClassResponseBuilder*) builder;
+ (SRXProtoSearchClassResponseBuilder*) builder;
+ (SRXProtoSearchClassResponseBuilder*) builderWithPrototype:(SRXProtoSearchClassResponse*) prototype;
- (SRXProtoSearchClassResponseBuilder*) toBuilder;

+ (SRXProtoSearchClassResponse*) parseFromData:(NSData*) data;
+ (SRXProtoSearchClassResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoSearchClassResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoSearchClassResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoSearchClassResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoSearchClassResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoSearchClassResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoSearchClassResponse* resultSrxprotoSearchClassResponse;
}

- (SRXProtoSearchClassResponse*) defaultInstance;

- (SRXProtoSearchClassResponseBuilder*) clear;
- (SRXProtoSearchClassResponseBuilder*) clone;

- (SRXProtoSearchClassResponse*) build;
- (SRXProtoSearchClassResponse*) buildPartial;

- (SRXProtoSearchClassResponseBuilder*) mergeFrom:(SRXProtoSearchClassResponse*) other;
- (SRXProtoSearchClassResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoSearchClassResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)classCollection;
- (SRXDataClassInfo*)classCollectionAtIndex:(NSUInteger)index;
- (SRXProtoSearchClassResponseBuilder *)addClassCollection:(SRXDataClassInfo*)value;
- (SRXProtoSearchClassResponseBuilder *)setClassCollectionArray:(NSArray *)array;
- (SRXProtoSearchClassResponseBuilder *)clearClassCollection;
@end

#define SRXProtoImage_data @"data"
@interface SRXProtoImage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasData_:1;
  NSData* data;
}
- (BOOL) hasData;
@property (readonly, strong) NSData* data;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoImageBuilder*) builder;
+ (SRXProtoImageBuilder*) builder;
+ (SRXProtoImageBuilder*) builderWithPrototype:(SRXProtoImage*) prototype;
- (SRXProtoImageBuilder*) toBuilder;

+ (SRXProtoImage*) parseFromData:(NSData*) data;
+ (SRXProtoImage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoImage*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoImage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoImage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoImage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoImageBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoImage* resultSrxprotoImage;
}

- (SRXProtoImage*) defaultInstance;

- (SRXProtoImageBuilder*) clear;
- (SRXProtoImageBuilder*) clone;

- (SRXProtoImage*) build;
- (SRXProtoImage*) buildPartial;

- (SRXProtoImageBuilder*) mergeFrom:(SRXProtoImage*) other;
- (SRXProtoImageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoImageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasData;
- (NSData*) data;
- (SRXProtoImageBuilder*) setData:(NSData*) value;
- (SRXProtoImageBuilder*) clearData;
@end

#define SRXProtoAddImagesRequest_requesting_user @"requestingUser"
#define SRXProtoAddImagesRequest_server_type @"serverType"
#define SRXProtoAddImagesRequest_image @"image"
@interface SRXProtoAddImagesRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRequestingUser_:1;
  BOOL hasServerType_:1;
  SRXDataUser* requestingUser;
  SRXDataImageServerTypeEnumImageServerType serverType;
  NSMutableArray * imageArray;
}
- (BOOL) hasRequestingUser;
- (BOOL) hasServerType;
@property (readonly, strong) SRXDataUser* requestingUser;
@property (readonly) SRXDataImageServerTypeEnumImageServerType serverType;
@property (readonly, strong) NSArray * image;
- (SRXDataImage*)imageAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoAddImagesRequestBuilder*) builder;
+ (SRXProtoAddImagesRequestBuilder*) builder;
+ (SRXProtoAddImagesRequestBuilder*) builderWithPrototype:(SRXProtoAddImagesRequest*) prototype;
- (SRXProtoAddImagesRequestBuilder*) toBuilder;

+ (SRXProtoAddImagesRequest*) parseFromData:(NSData*) data;
+ (SRXProtoAddImagesRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoAddImagesRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoAddImagesRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoAddImagesRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoAddImagesRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoAddImagesRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoAddImagesRequest* resultSrxprotoAddImagesRequest;
}

- (SRXProtoAddImagesRequest*) defaultInstance;

- (SRXProtoAddImagesRequestBuilder*) clear;
- (SRXProtoAddImagesRequestBuilder*) clone;

- (SRXProtoAddImagesRequest*) build;
- (SRXProtoAddImagesRequest*) buildPartial;

- (SRXProtoAddImagesRequestBuilder*) mergeFrom:(SRXProtoAddImagesRequest*) other;
- (SRXProtoAddImagesRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoAddImagesRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRequestingUser;
- (SRXDataUser*) requestingUser;
- (SRXProtoAddImagesRequestBuilder*) setRequestingUser:(SRXDataUser*) value;
- (SRXProtoAddImagesRequestBuilder*) setRequestingUserBuilder:(SRXDataUserBuilder*) builderForValue;
- (SRXProtoAddImagesRequestBuilder*) mergeRequestingUser:(SRXDataUser*) value;
- (SRXProtoAddImagesRequestBuilder*) clearRequestingUser;

- (BOOL) hasServerType;
- (SRXDataImageServerTypeEnumImageServerType) serverType;
- (SRXProtoAddImagesRequestBuilder*) setServerType:(SRXDataImageServerTypeEnumImageServerType) value;
- (SRXProtoAddImagesRequestBuilder*) clearServerType;

- (NSMutableArray *)image;
- (SRXDataImage*)imageAtIndex:(NSUInteger)index;
- (SRXProtoAddImagesRequestBuilder *)addImage:(SRXDataImage*)value;
- (SRXProtoAddImagesRequestBuilder *)setImageArray:(NSArray *)array;
- (SRXProtoAddImagesRequestBuilder *)clearImage;
@end

#define SRXProtoAddImagesResponse_image_key @"imageKey"
@interface SRXProtoAddImagesResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * imageKeyArray;
}
@property (readonly, strong) NSArray * imageKey;
- (NSString*)imageKeyAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoAddImagesResponseBuilder*) builder;
+ (SRXProtoAddImagesResponseBuilder*) builder;
+ (SRXProtoAddImagesResponseBuilder*) builderWithPrototype:(SRXProtoAddImagesResponse*) prototype;
- (SRXProtoAddImagesResponseBuilder*) toBuilder;

+ (SRXProtoAddImagesResponse*) parseFromData:(NSData*) data;
+ (SRXProtoAddImagesResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoAddImagesResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoAddImagesResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoAddImagesResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoAddImagesResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoAddImagesResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoAddImagesResponse* resultSrxprotoAddImagesResponse;
}

- (SRXProtoAddImagesResponse*) defaultInstance;

- (SRXProtoAddImagesResponseBuilder*) clear;
- (SRXProtoAddImagesResponseBuilder*) clone;

- (SRXProtoAddImagesResponse*) build;
- (SRXProtoAddImagesResponse*) buildPartial;

- (SRXProtoAddImagesResponseBuilder*) mergeFrom:(SRXProtoAddImagesResponse*) other;
- (SRXProtoAddImagesResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoAddImagesResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)imageKey;
- (NSString*)imageKeyAtIndex:(NSUInteger)index;
- (SRXProtoAddImagesResponseBuilder *)addImageKey:(NSString*)value;
- (SRXProtoAddImagesResponseBuilder *)setImageKeyArray:(NSArray *)array;
- (SRXProtoAddImagesResponseBuilder *)clearImageKey;
@end

#define SRXProtoGetImagesRequest_server_type @"serverType"
#define SRXProtoGetImagesRequest_image_key @"imageKey"
@interface SRXProtoGetImagesRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasServerType_:1;
  SRXDataImageServerTypeEnumImageServerType serverType;
  NSMutableArray * imageKeyArray;
}
- (BOOL) hasServerType;
@property (readonly) SRXDataImageServerTypeEnumImageServerType serverType;
@property (readonly, strong) NSArray * imageKey;
- (NSString*)imageKeyAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoGetImagesRequestBuilder*) builder;
+ (SRXProtoGetImagesRequestBuilder*) builder;
+ (SRXProtoGetImagesRequestBuilder*) builderWithPrototype:(SRXProtoGetImagesRequest*) prototype;
- (SRXProtoGetImagesRequestBuilder*) toBuilder;

+ (SRXProtoGetImagesRequest*) parseFromData:(NSData*) data;
+ (SRXProtoGetImagesRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoGetImagesRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoGetImagesRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoGetImagesRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoGetImagesRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoGetImagesRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoGetImagesRequest* resultSrxprotoGetImagesRequest;
}

- (SRXProtoGetImagesRequest*) defaultInstance;

- (SRXProtoGetImagesRequestBuilder*) clear;
- (SRXProtoGetImagesRequestBuilder*) clone;

- (SRXProtoGetImagesRequest*) build;
- (SRXProtoGetImagesRequest*) buildPartial;

- (SRXProtoGetImagesRequestBuilder*) mergeFrom:(SRXProtoGetImagesRequest*) other;
- (SRXProtoGetImagesRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoGetImagesRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasServerType;
- (SRXDataImageServerTypeEnumImageServerType) serverType;
- (SRXProtoGetImagesRequestBuilder*) setServerType:(SRXDataImageServerTypeEnumImageServerType) value;
- (SRXProtoGetImagesRequestBuilder*) clearServerType;

- (NSMutableArray *)imageKey;
- (NSString*)imageKeyAtIndex:(NSUInteger)index;
- (SRXProtoGetImagesRequestBuilder *)addImageKey:(NSString*)value;
- (SRXProtoGetImagesRequestBuilder *)setImageKeyArray:(NSArray *)array;
- (SRXProtoGetImagesRequestBuilder *)clearImageKey;
@end

#define SRXProtoGetImagesResponse_image_data @"imageData"
@interface SRXProtoGetImagesResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * imageDataArray;
}
@property (readonly, strong) NSArray * imageData;
- (SRXDataImage*)imageDataAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoGetImagesResponseBuilder*) builder;
+ (SRXProtoGetImagesResponseBuilder*) builder;
+ (SRXProtoGetImagesResponseBuilder*) builderWithPrototype:(SRXProtoGetImagesResponse*) prototype;
- (SRXProtoGetImagesResponseBuilder*) toBuilder;

+ (SRXProtoGetImagesResponse*) parseFromData:(NSData*) data;
+ (SRXProtoGetImagesResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoGetImagesResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoGetImagesResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoGetImagesResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoGetImagesResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoGetImagesResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoGetImagesResponse* resultSrxprotoGetImagesResponse;
}

- (SRXProtoGetImagesResponse*) defaultInstance;

- (SRXProtoGetImagesResponseBuilder*) clear;
- (SRXProtoGetImagesResponseBuilder*) clone;

- (SRXProtoGetImagesResponse*) build;
- (SRXProtoGetImagesResponse*) buildPartial;

- (SRXProtoGetImagesResponseBuilder*) mergeFrom:(SRXProtoGetImagesResponse*) other;
- (SRXProtoGetImagesResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoGetImagesResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)imageData;
- (SRXDataImage*)imageDataAtIndex:(NSUInteger)index;
- (SRXProtoGetImagesResponseBuilder *)addImageData:(SRXDataImage*)value;
- (SRXProtoGetImagesResponseBuilder *)setImageDataArray:(NSArray *)array;
- (SRXProtoGetImagesResponseBuilder *)clearImageData;
@end

#define SRXProtoGetOwnedSchoolRequest_requesting_user @"requestingUser"
@interface SRXProtoGetOwnedSchoolRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRequestingUser_:1;
  SRXDataUser* requestingUser;
}
- (BOOL) hasRequestingUser;
@property (readonly, strong) SRXDataUser* requestingUser;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoGetOwnedSchoolRequestBuilder*) builder;
+ (SRXProtoGetOwnedSchoolRequestBuilder*) builder;
+ (SRXProtoGetOwnedSchoolRequestBuilder*) builderWithPrototype:(SRXProtoGetOwnedSchoolRequest*) prototype;
- (SRXProtoGetOwnedSchoolRequestBuilder*) toBuilder;

+ (SRXProtoGetOwnedSchoolRequest*) parseFromData:(NSData*) data;
+ (SRXProtoGetOwnedSchoolRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoGetOwnedSchoolRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoGetOwnedSchoolRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoGetOwnedSchoolRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoGetOwnedSchoolRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoGetOwnedSchoolRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoGetOwnedSchoolRequest* resultSrxprotoGetOwnedSchoolRequest;
}

- (SRXProtoGetOwnedSchoolRequest*) defaultInstance;

- (SRXProtoGetOwnedSchoolRequestBuilder*) clear;
- (SRXProtoGetOwnedSchoolRequestBuilder*) clone;

- (SRXProtoGetOwnedSchoolRequest*) build;
- (SRXProtoGetOwnedSchoolRequest*) buildPartial;

- (SRXProtoGetOwnedSchoolRequestBuilder*) mergeFrom:(SRXProtoGetOwnedSchoolRequest*) other;
- (SRXProtoGetOwnedSchoolRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoGetOwnedSchoolRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRequestingUser;
- (SRXDataUser*) requestingUser;
- (SRXProtoGetOwnedSchoolRequestBuilder*) setRequestingUser:(SRXDataUser*) value;
- (SRXProtoGetOwnedSchoolRequestBuilder*) setRequestingUserBuilder:(SRXDataUserBuilder*) builderForValue;
- (SRXProtoGetOwnedSchoolRequestBuilder*) mergeRequestingUser:(SRXDataUser*) value;
- (SRXProtoGetOwnedSchoolRequestBuilder*) clearRequestingUser;
@end

#define SRXProtoGetOwnedSchoolResponse_school @"school"
@interface SRXProtoGetOwnedSchoolResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * schoolArray;
}
@property (readonly, strong) NSArray * school;
- (SRXDataSchool*)schoolAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoGetOwnedSchoolResponseBuilder*) builder;
+ (SRXProtoGetOwnedSchoolResponseBuilder*) builder;
+ (SRXProtoGetOwnedSchoolResponseBuilder*) builderWithPrototype:(SRXProtoGetOwnedSchoolResponse*) prototype;
- (SRXProtoGetOwnedSchoolResponseBuilder*) toBuilder;

+ (SRXProtoGetOwnedSchoolResponse*) parseFromData:(NSData*) data;
+ (SRXProtoGetOwnedSchoolResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoGetOwnedSchoolResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoGetOwnedSchoolResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoGetOwnedSchoolResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoGetOwnedSchoolResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoGetOwnedSchoolResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoGetOwnedSchoolResponse* resultSrxprotoGetOwnedSchoolResponse;
}

- (SRXProtoGetOwnedSchoolResponse*) defaultInstance;

- (SRXProtoGetOwnedSchoolResponseBuilder*) clear;
- (SRXProtoGetOwnedSchoolResponseBuilder*) clone;

- (SRXProtoGetOwnedSchoolResponse*) build;
- (SRXProtoGetOwnedSchoolResponse*) buildPartial;

- (SRXProtoGetOwnedSchoolResponseBuilder*) mergeFrom:(SRXProtoGetOwnedSchoolResponse*) other;
- (SRXProtoGetOwnedSchoolResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoGetOwnedSchoolResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)school;
- (SRXDataSchool*)schoolAtIndex:(NSUInteger)index;
- (SRXProtoGetOwnedSchoolResponseBuilder *)addSchool:(SRXDataSchool*)value;
- (SRXProtoGetOwnedSchoolResponseBuilder *)setSchoolArray:(NSArray *)array;
- (SRXProtoGetOwnedSchoolResponseBuilder *)clearSchool;
@end

#define SRXProtoCreateSchoolRequest_requesting_user @"requestingUser"
#define SRXProtoCreateSchoolRequest_school_info @"schoolInfo"
@interface SRXProtoCreateSchoolRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRequestingUser_:1;
  BOOL hasSchoolInfo_:1;
  SRXDataUser* requestingUser;
  SRXDataSchoolInfo* schoolInfo;
}
- (BOOL) hasRequestingUser;
- (BOOL) hasSchoolInfo;
@property (readonly, strong) SRXDataUser* requestingUser;
@property (readonly, strong) SRXDataSchoolInfo* schoolInfo;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoCreateSchoolRequestBuilder*) builder;
+ (SRXProtoCreateSchoolRequestBuilder*) builder;
+ (SRXProtoCreateSchoolRequestBuilder*) builderWithPrototype:(SRXProtoCreateSchoolRequest*) prototype;
- (SRXProtoCreateSchoolRequestBuilder*) toBuilder;

+ (SRXProtoCreateSchoolRequest*) parseFromData:(NSData*) data;
+ (SRXProtoCreateSchoolRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoCreateSchoolRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoCreateSchoolRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoCreateSchoolRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoCreateSchoolRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoCreateSchoolRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoCreateSchoolRequest* resultSrxprotoCreateSchoolRequest;
}

- (SRXProtoCreateSchoolRequest*) defaultInstance;

- (SRXProtoCreateSchoolRequestBuilder*) clear;
- (SRXProtoCreateSchoolRequestBuilder*) clone;

- (SRXProtoCreateSchoolRequest*) build;
- (SRXProtoCreateSchoolRequest*) buildPartial;

- (SRXProtoCreateSchoolRequestBuilder*) mergeFrom:(SRXProtoCreateSchoolRequest*) other;
- (SRXProtoCreateSchoolRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoCreateSchoolRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRequestingUser;
- (SRXDataUser*) requestingUser;
- (SRXProtoCreateSchoolRequestBuilder*) setRequestingUser:(SRXDataUser*) value;
- (SRXProtoCreateSchoolRequestBuilder*) setRequestingUserBuilder:(SRXDataUserBuilder*) builderForValue;
- (SRXProtoCreateSchoolRequestBuilder*) mergeRequestingUser:(SRXDataUser*) value;
- (SRXProtoCreateSchoolRequestBuilder*) clearRequestingUser;

- (BOOL) hasSchoolInfo;
- (SRXDataSchoolInfo*) schoolInfo;
- (SRXProtoCreateSchoolRequestBuilder*) setSchoolInfo:(SRXDataSchoolInfo*) value;
- (SRXProtoCreateSchoolRequestBuilder*) setSchoolInfoBuilder:(SRXDataSchoolInfoBuilder*) builderForValue;
- (SRXProtoCreateSchoolRequestBuilder*) mergeSchoolInfo:(SRXDataSchoolInfo*) value;
- (SRXProtoCreateSchoolRequestBuilder*) clearSchoolInfo;
@end

#define SRXProtoCreateSchoolResponse_school_id @"schoolId"
@interface SRXProtoCreateSchoolResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSchoolId_:1;
  NSString* schoolId;
}
- (BOOL) hasSchoolId;
@property (readonly, strong) NSString* schoolId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoCreateSchoolResponseBuilder*) builder;
+ (SRXProtoCreateSchoolResponseBuilder*) builder;
+ (SRXProtoCreateSchoolResponseBuilder*) builderWithPrototype:(SRXProtoCreateSchoolResponse*) prototype;
- (SRXProtoCreateSchoolResponseBuilder*) toBuilder;

+ (SRXProtoCreateSchoolResponse*) parseFromData:(NSData*) data;
+ (SRXProtoCreateSchoolResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoCreateSchoolResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoCreateSchoolResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoCreateSchoolResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoCreateSchoolResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoCreateSchoolResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoCreateSchoolResponse* resultSrxprotoCreateSchoolResponse;
}

- (SRXProtoCreateSchoolResponse*) defaultInstance;

- (SRXProtoCreateSchoolResponseBuilder*) clear;
- (SRXProtoCreateSchoolResponseBuilder*) clone;

- (SRXProtoCreateSchoolResponse*) build;
- (SRXProtoCreateSchoolResponse*) buildPartial;

- (SRXProtoCreateSchoolResponseBuilder*) mergeFrom:(SRXProtoCreateSchoolResponse*) other;
- (SRXProtoCreateSchoolResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoCreateSchoolResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSchoolId;
- (NSString*) schoolId;
- (SRXProtoCreateSchoolResponseBuilder*) setSchoolId:(NSString*) value;
- (SRXProtoCreateSchoolResponseBuilder*) clearSchoolId;
@end

@interface SRXProtoReadProfileRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoReadProfileRequestBuilder*) builder;
+ (SRXProtoReadProfileRequestBuilder*) builder;
+ (SRXProtoReadProfileRequestBuilder*) builderWithPrototype:(SRXProtoReadProfileRequest*) prototype;
- (SRXProtoReadProfileRequestBuilder*) toBuilder;

+ (SRXProtoReadProfileRequest*) parseFromData:(NSData*) data;
+ (SRXProtoReadProfileRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoReadProfileRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoReadProfileRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoReadProfileRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoReadProfileRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoReadProfileRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoReadProfileRequest* resultSrxprotoReadProfileRequest;
}

- (SRXProtoReadProfileRequest*) defaultInstance;

- (SRXProtoReadProfileRequestBuilder*) clear;
- (SRXProtoReadProfileRequestBuilder*) clone;

- (SRXProtoReadProfileRequest*) build;
- (SRXProtoReadProfileRequest*) buildPartial;

- (SRXProtoReadProfileRequestBuilder*) mergeFrom:(SRXProtoReadProfileRequest*) other;
- (SRXProtoReadProfileRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoReadProfileRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoGetProfileResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoGetProfileResponseBuilder*) builder;
+ (SRXProtoGetProfileResponseBuilder*) builder;
+ (SRXProtoGetProfileResponseBuilder*) builderWithPrototype:(SRXProtoGetProfileResponse*) prototype;
- (SRXProtoGetProfileResponseBuilder*) toBuilder;

+ (SRXProtoGetProfileResponse*) parseFromData:(NSData*) data;
+ (SRXProtoGetProfileResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoGetProfileResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoGetProfileResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoGetProfileResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoGetProfileResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoGetProfileResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoGetProfileResponse* resultSrxprotoGetProfileResponse;
}

- (SRXProtoGetProfileResponse*) defaultInstance;

- (SRXProtoGetProfileResponseBuilder*) clear;
- (SRXProtoGetProfileResponseBuilder*) clone;

- (SRXProtoGetProfileResponse*) build;
- (SRXProtoGetProfileResponse*) buildPartial;

- (SRXProtoGetProfileResponseBuilder*) mergeFrom:(SRXProtoGetProfileResponse*) other;
- (SRXProtoGetProfileResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoGetProfileResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoMutableProfileRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoMutableProfileRequestBuilder*) builder;
+ (SRXProtoMutableProfileRequestBuilder*) builder;
+ (SRXProtoMutableProfileRequestBuilder*) builderWithPrototype:(SRXProtoMutableProfileRequest*) prototype;
- (SRXProtoMutableProfileRequestBuilder*) toBuilder;

+ (SRXProtoMutableProfileRequest*) parseFromData:(NSData*) data;
+ (SRXProtoMutableProfileRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoMutableProfileRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoMutableProfileRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoMutableProfileRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoMutableProfileRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoMutableProfileRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoMutableProfileRequest* resultSrxprotoMutableProfileRequest;
}

- (SRXProtoMutableProfileRequest*) defaultInstance;

- (SRXProtoMutableProfileRequestBuilder*) clear;
- (SRXProtoMutableProfileRequestBuilder*) clone;

- (SRXProtoMutableProfileRequest*) build;
- (SRXProtoMutableProfileRequest*) buildPartial;

- (SRXProtoMutableProfileRequestBuilder*) mergeFrom:(SRXProtoMutableProfileRequest*) other;
- (SRXProtoMutableProfileRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoMutableProfileRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoMutableProfileResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoMutableProfileResponseBuilder*) builder;
+ (SRXProtoMutableProfileResponseBuilder*) builder;
+ (SRXProtoMutableProfileResponseBuilder*) builderWithPrototype:(SRXProtoMutableProfileResponse*) prototype;
- (SRXProtoMutableProfileResponseBuilder*) toBuilder;

+ (SRXProtoMutableProfileResponse*) parseFromData:(NSData*) data;
+ (SRXProtoMutableProfileResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoMutableProfileResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoMutableProfileResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoMutableProfileResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoMutableProfileResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoMutableProfileResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoMutableProfileResponse* resultSrxprotoMutableProfileResponse;
}

- (SRXProtoMutableProfileResponse*) defaultInstance;

- (SRXProtoMutableProfileResponseBuilder*) clear;
- (SRXProtoMutableProfileResponseBuilder*) clone;

- (SRXProtoMutableProfileResponse*) build;
- (SRXProtoMutableProfileResponse*) buildPartial;

- (SRXProtoMutableProfileResponseBuilder*) mergeFrom:(SRXProtoMutableProfileResponse*) other;
- (SRXProtoMutableProfileResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoMutableProfileResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define SRXProtoNativeLogInMessage_user_name @"userName"
#define SRXProtoNativeLogInMessage_password @"password"
@interface SRXProtoNativeLogInMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserName_:1;
  BOOL hasPassword_:1;
  NSString* userName;
  NSString* password;
}
- (BOOL) hasUserName;
- (BOOL) hasPassword;
@property (readonly, strong) NSString* userName;
@property (readonly, strong) NSString* password;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoNativeLogInMessageBuilder*) builder;
+ (SRXProtoNativeLogInMessageBuilder*) builder;
+ (SRXProtoNativeLogInMessageBuilder*) builderWithPrototype:(SRXProtoNativeLogInMessage*) prototype;
- (SRXProtoNativeLogInMessageBuilder*) toBuilder;

+ (SRXProtoNativeLogInMessage*) parseFromData:(NSData*) data;
+ (SRXProtoNativeLogInMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoNativeLogInMessage*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoNativeLogInMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoNativeLogInMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoNativeLogInMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoNativeLogInMessageBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoNativeLogInMessage* resultSrxprotoNativeLogInMessage;
}

- (SRXProtoNativeLogInMessage*) defaultInstance;

- (SRXProtoNativeLogInMessageBuilder*) clear;
- (SRXProtoNativeLogInMessageBuilder*) clone;

- (SRXProtoNativeLogInMessage*) build;
- (SRXProtoNativeLogInMessage*) buildPartial;

- (SRXProtoNativeLogInMessageBuilder*) mergeFrom:(SRXProtoNativeLogInMessage*) other;
- (SRXProtoNativeLogInMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoNativeLogInMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserName;
- (NSString*) userName;
- (SRXProtoNativeLogInMessageBuilder*) setUserName:(NSString*) value;
- (SRXProtoNativeLogInMessageBuilder*) clearUserName;

- (BOOL) hasPassword;
- (NSString*) password;
- (SRXProtoNativeLogInMessageBuilder*) setPassword:(NSString*) value;
- (SRXProtoNativeLogInMessageBuilder*) clearPassword;
@end

#define SRXProtoLogInRequest_log_in_method @"logInMethod"
#define SRXProtoLogInRequest_native_log_in @"nativeLogIn"
@interface SRXProtoLogInRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasNativeLogIn_:1;
  BOOL hasLogInMethod_:1;
  SRXProtoNativeLogInMessage* nativeLogIn;
  SRXProtoLogInMethodEnum logInMethod;
}
- (BOOL) hasLogInMethod;
- (BOOL) hasNativeLogIn;
@property (readonly) SRXProtoLogInMethodEnum logInMethod;
@property (readonly, strong) SRXProtoNativeLogInMessage* nativeLogIn;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoLogInRequestBuilder*) builder;
+ (SRXProtoLogInRequestBuilder*) builder;
+ (SRXProtoLogInRequestBuilder*) builderWithPrototype:(SRXProtoLogInRequest*) prototype;
- (SRXProtoLogInRequestBuilder*) toBuilder;

+ (SRXProtoLogInRequest*) parseFromData:(NSData*) data;
+ (SRXProtoLogInRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoLogInRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoLogInRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoLogInRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoLogInRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoLogInRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoLogInRequest* resultSrxprotoLogInRequest;
}

- (SRXProtoLogInRequest*) defaultInstance;

- (SRXProtoLogInRequestBuilder*) clear;
- (SRXProtoLogInRequestBuilder*) clone;

- (SRXProtoLogInRequest*) build;
- (SRXProtoLogInRequest*) buildPartial;

- (SRXProtoLogInRequestBuilder*) mergeFrom:(SRXProtoLogInRequest*) other;
- (SRXProtoLogInRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoLogInRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLogInMethod;
- (SRXProtoLogInMethodEnum) logInMethod;
- (SRXProtoLogInRequestBuilder*) setLogInMethod:(SRXProtoLogInMethodEnum) value;
- (SRXProtoLogInRequestBuilder*) clearLogInMethod;

- (BOOL) hasNativeLogIn;
- (SRXProtoNativeLogInMessage*) nativeLogIn;
- (SRXProtoLogInRequestBuilder*) setNativeLogIn:(SRXProtoNativeLogInMessage*) value;
- (SRXProtoLogInRequestBuilder*) setNativeLogInBuilder:(SRXProtoNativeLogInMessageBuilder*) builderForValue;
- (SRXProtoLogInRequestBuilder*) mergeNativeLogIn:(SRXProtoNativeLogInMessage*) value;
- (SRXProtoLogInRequestBuilder*) clearNativeLogIn;
@end

#define SRXProtoLogInResponse_user @"user"
@interface SRXProtoLogInResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUser_:1;
  SRXDataUser* user;
}
- (BOOL) hasUser;
@property (readonly, strong) SRXDataUser* user;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoLogInResponseBuilder*) builder;
+ (SRXProtoLogInResponseBuilder*) builder;
+ (SRXProtoLogInResponseBuilder*) builderWithPrototype:(SRXProtoLogInResponse*) prototype;
- (SRXProtoLogInResponseBuilder*) toBuilder;

+ (SRXProtoLogInResponse*) parseFromData:(NSData*) data;
+ (SRXProtoLogInResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoLogInResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoLogInResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoLogInResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoLogInResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoLogInResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoLogInResponse* resultSrxprotoLogInResponse;
}

- (SRXProtoLogInResponse*) defaultInstance;

- (SRXProtoLogInResponseBuilder*) clear;
- (SRXProtoLogInResponseBuilder*) clone;

- (SRXProtoLogInResponse*) build;
- (SRXProtoLogInResponse*) buildPartial;

- (SRXProtoLogInResponseBuilder*) mergeFrom:(SRXProtoLogInResponse*) other;
- (SRXProtoLogInResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoLogInResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUser;
- (SRXDataUser*) user;
- (SRXProtoLogInResponseBuilder*) setUser:(SRXDataUser*) value;
- (SRXProtoLogInResponseBuilder*) setUserBuilder:(SRXDataUserBuilder*) builderForValue;
- (SRXProtoLogInResponseBuilder*) mergeUser:(SRXDataUser*) value;
- (SRXProtoLogInResponseBuilder*) clearUser;
@end


// @@protoc_insertion_point(global_scope)
