// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "SRXDataClass.pb.h"
// @@protoc_insertion_point(imports)

@class SRXDataClass;
@class SRXDataClassBuilder;
@class SRXDataClassInfo;
@class SRXDataClassInfoBuilder;
@class SRXDataClassTime;
@class SRXDataClassTimeBuilder;
@class SRXDataClassTypeEnum;
@class SRXDataClassTypeEnumBuilder;
@class SRXDataLocation;
@class SRXDataLocationBuilder;
@class SRXDataRoleInClassTypeEnum;
@class SRXDataRoleInClassTypeEnumBuilder;
@class SRXDataUser;
@class SRXDataUserBuilder;
@class SRXProtoCreateClassRequest;
@class SRXProtoCreateClassRequestBuilder;
@class SRXProtoCreateClassResponse;
@class SRXProtoCreateClassResponseBuilder;
@class SRXProtoLogInRequest;
@class SRXProtoLogInRequestBuilder;
@class SRXProtoLogInResponse;
@class SRXProtoLogInResponseBuilder;
@class SRXProtoNativeLogInMessage;
@class SRXProtoNativeLogInMessageBuilder;
@class SRXProtoReadClassRequest;
@class SRXProtoReadClassRequestBuilder;
@class SRXProtoReadClassResponse;
@class SRXProtoReadClassResponseBuilder;
@class SRXProtoSearchClassRequest;
@class SRXProtoSearchClassRequestBuilder;
@class SRXProtoSearchClassResponse;
@class SRXProtoSearchClassResponseBuilder;


typedef NS_ENUM(SInt32, SRXProtoLogInMethodEnum) {
  SRXProtoLogInMethodEnumDefault = 0,
  SRXProtoLogInMethodEnumNative = 1,
};

BOOL SRXProtoLogInMethodEnumIsValidValue(SRXProtoLogInMethodEnum value);
NSString *NSStringFromSRXProtoLogInMethodEnum(SRXProtoLogInMethodEnum value);

typedef NS_ENUM(SInt32, SRXDataRoleInClassTypeEnumSRXDataRoleInClassType) {
  SRXDataRoleInClassTypeEnumSRXDataRoleInClassTypeUnknown = 0,
  SRXDataRoleInClassTypeEnumSRXDataRoleInClassTypeOwner = 1,
  SRXDataRoleInClassTypeEnumSRXDataRoleInClassTypeStudent = 2,
};

BOOL SRXDataRoleInClassTypeEnumSRXDataRoleInClassTypeIsValidValue(SRXDataRoleInClassTypeEnumSRXDataRoleInClassType value);
NSString *NSStringFromSRXDataRoleInClassTypeEnumSRXDataRoleInClassType(SRXDataRoleInClassTypeEnumSRXDataRoleInClassType value);


@interface SrxapiRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define SRXDataUser_id @"id"
@interface SRXDataUser : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  NSString* id;
}
- (BOOL) hasId;
@property (readonly, strong) NSString* id;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXDataUserBuilder*) builder;
+ (SRXDataUserBuilder*) builder;
+ (SRXDataUserBuilder*) builderWithPrototype:(SRXDataUser*) prototype;
- (SRXDataUserBuilder*) toBuilder;

+ (SRXDataUser*) parseFromData:(NSData*) data;
+ (SRXDataUser*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataUser*) parseFromInputStream:(NSInputStream*) input;
+ (SRXDataUser*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataUser*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXDataUser*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXDataUserBuilder : PBGeneratedMessageBuilder {
@private
  SRXDataUser* resultSrxdataUser;
}

- (SRXDataUser*) defaultInstance;

- (SRXDataUserBuilder*) clear;
- (SRXDataUserBuilder*) clone;

- (SRXDataUser*) build;
- (SRXDataUser*) buildPartial;

- (SRXDataUserBuilder*) mergeFrom:(SRXDataUser*) other;
- (SRXDataUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXDataUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (SRXDataUserBuilder*) setId:(NSString*) value;
- (SRXDataUserBuilder*) clearId;
@end

#define SRXProtoCreateClassRequest_requesting_user @"requestingUser"
#define SRXProtoCreateClassRequest_class_info @"classInfo"
@interface SRXProtoCreateClassRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRequestingUser_:1;
  BOOL hasClassInfo_:1;
  SRXDataUser* requestingUser;
  SRXDataClassInfo* classInfo;
}
- (BOOL) hasRequestingUser;
- (BOOL) hasClassInfo;
@property (readonly, strong) SRXDataUser* requestingUser;
@property (readonly, strong) SRXDataClassInfo* classInfo;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoCreateClassRequestBuilder*) builder;
+ (SRXProtoCreateClassRequestBuilder*) builder;
+ (SRXProtoCreateClassRequestBuilder*) builderWithPrototype:(SRXProtoCreateClassRequest*) prototype;
- (SRXProtoCreateClassRequestBuilder*) toBuilder;

+ (SRXProtoCreateClassRequest*) parseFromData:(NSData*) data;
+ (SRXProtoCreateClassRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoCreateClassRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoCreateClassRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoCreateClassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoCreateClassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoCreateClassRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoCreateClassRequest* resultSrxprotoCreateClassRequest;
}

- (SRXProtoCreateClassRequest*) defaultInstance;

- (SRXProtoCreateClassRequestBuilder*) clear;
- (SRXProtoCreateClassRequestBuilder*) clone;

- (SRXProtoCreateClassRequest*) build;
- (SRXProtoCreateClassRequest*) buildPartial;

- (SRXProtoCreateClassRequestBuilder*) mergeFrom:(SRXProtoCreateClassRequest*) other;
- (SRXProtoCreateClassRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoCreateClassRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRequestingUser;
- (SRXDataUser*) requestingUser;
- (SRXProtoCreateClassRequestBuilder*) setRequestingUser:(SRXDataUser*) value;
- (SRXProtoCreateClassRequestBuilder*) setRequestingUserBuilder:(SRXDataUserBuilder*) builderForValue;
- (SRXProtoCreateClassRequestBuilder*) mergeRequestingUser:(SRXDataUser*) value;
- (SRXProtoCreateClassRequestBuilder*) clearRequestingUser;

- (BOOL) hasClassInfo;
- (SRXDataClassInfo*) classInfo;
- (SRXProtoCreateClassRequestBuilder*) setClassInfo:(SRXDataClassInfo*) value;
- (SRXProtoCreateClassRequestBuilder*) setClassInfoBuilder:(SRXDataClassInfoBuilder*) builderForValue;
- (SRXProtoCreateClassRequestBuilder*) mergeClassInfo:(SRXDataClassInfo*) value;
- (SRXProtoCreateClassRequestBuilder*) clearClassInfo;
@end

#define SRXProtoCreateClassResponse_class_id @"classId"
@interface SRXProtoCreateClassResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasClassId_:1;
  NSString* classId;
}
- (BOOL) hasClassId;
@property (readonly, strong) NSString* classId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoCreateClassResponseBuilder*) builder;
+ (SRXProtoCreateClassResponseBuilder*) builder;
+ (SRXProtoCreateClassResponseBuilder*) builderWithPrototype:(SRXProtoCreateClassResponse*) prototype;
- (SRXProtoCreateClassResponseBuilder*) toBuilder;

+ (SRXProtoCreateClassResponse*) parseFromData:(NSData*) data;
+ (SRXProtoCreateClassResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoCreateClassResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoCreateClassResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoCreateClassResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoCreateClassResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoCreateClassResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoCreateClassResponse* resultSrxprotoCreateClassResponse;
}

- (SRXProtoCreateClassResponse*) defaultInstance;

- (SRXProtoCreateClassResponseBuilder*) clear;
- (SRXProtoCreateClassResponseBuilder*) clone;

- (SRXProtoCreateClassResponse*) build;
- (SRXProtoCreateClassResponse*) buildPartial;

- (SRXProtoCreateClassResponseBuilder*) mergeFrom:(SRXProtoCreateClassResponse*) other;
- (SRXProtoCreateClassResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoCreateClassResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasClassId;
- (NSString*) classId;
- (SRXProtoCreateClassResponseBuilder*) setClassId:(NSString*) value;
- (SRXProtoCreateClassResponseBuilder*) clearClassId;
@end

@interface SRXDataRoleInClassTypeEnum : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXDataRoleInClassTypeEnumBuilder*) builder;
+ (SRXDataRoleInClassTypeEnumBuilder*) builder;
+ (SRXDataRoleInClassTypeEnumBuilder*) builderWithPrototype:(SRXDataRoleInClassTypeEnum*) prototype;
- (SRXDataRoleInClassTypeEnumBuilder*) toBuilder;

+ (SRXDataRoleInClassTypeEnum*) parseFromData:(NSData*) data;
+ (SRXDataRoleInClassTypeEnum*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataRoleInClassTypeEnum*) parseFromInputStream:(NSInputStream*) input;
+ (SRXDataRoleInClassTypeEnum*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataRoleInClassTypeEnum*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXDataRoleInClassTypeEnum*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXDataRoleInClassTypeEnumBuilder : PBGeneratedMessageBuilder {
@private
  SRXDataRoleInClassTypeEnum* resultSrxdataRoleInClassTypeEnum;
}

- (SRXDataRoleInClassTypeEnum*) defaultInstance;

- (SRXDataRoleInClassTypeEnumBuilder*) clear;
- (SRXDataRoleInClassTypeEnumBuilder*) clone;

- (SRXDataRoleInClassTypeEnum*) build;
- (SRXDataRoleInClassTypeEnum*) buildPartial;

- (SRXDataRoleInClassTypeEnumBuilder*) mergeFrom:(SRXDataRoleInClassTypeEnum*) other;
- (SRXDataRoleInClassTypeEnumBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXDataRoleInClassTypeEnumBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define SRXProtoReadClassRequest_requesting_user @"requestingUser"
#define SRXProtoReadClassRequest_role_in_class @"roleInClass"
@interface SRXProtoReadClassRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRequestingUser_:1;
  BOOL hasRoleInClass_:1;
  SRXDataUser* requestingUser;
  SRXDataRoleInClassTypeEnumSRXDataRoleInClassType roleInClass;
}
- (BOOL) hasRequestingUser;
- (BOOL) hasRoleInClass;
@property (readonly, strong) SRXDataUser* requestingUser;
@property (readonly) SRXDataRoleInClassTypeEnumSRXDataRoleInClassType roleInClass;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoReadClassRequestBuilder*) builder;
+ (SRXProtoReadClassRequestBuilder*) builder;
+ (SRXProtoReadClassRequestBuilder*) builderWithPrototype:(SRXProtoReadClassRequest*) prototype;
- (SRXProtoReadClassRequestBuilder*) toBuilder;

+ (SRXProtoReadClassRequest*) parseFromData:(NSData*) data;
+ (SRXProtoReadClassRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoReadClassRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoReadClassRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoReadClassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoReadClassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoReadClassRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoReadClassRequest* resultSrxprotoReadClassRequest;
}

- (SRXProtoReadClassRequest*) defaultInstance;

- (SRXProtoReadClassRequestBuilder*) clear;
- (SRXProtoReadClassRequestBuilder*) clone;

- (SRXProtoReadClassRequest*) build;
- (SRXProtoReadClassRequest*) buildPartial;

- (SRXProtoReadClassRequestBuilder*) mergeFrom:(SRXProtoReadClassRequest*) other;
- (SRXProtoReadClassRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoReadClassRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRequestingUser;
- (SRXDataUser*) requestingUser;
- (SRXProtoReadClassRequestBuilder*) setRequestingUser:(SRXDataUser*) value;
- (SRXProtoReadClassRequestBuilder*) setRequestingUserBuilder:(SRXDataUserBuilder*) builderForValue;
- (SRXProtoReadClassRequestBuilder*) mergeRequestingUser:(SRXDataUser*) value;
- (SRXProtoReadClassRequestBuilder*) clearRequestingUser;

- (BOOL) hasRoleInClass;
- (SRXDataRoleInClassTypeEnumSRXDataRoleInClassType) roleInClass;
- (SRXProtoReadClassRequestBuilder*) setRoleInClass:(SRXDataRoleInClassTypeEnumSRXDataRoleInClassType) value;
- (SRXProtoReadClassRequestBuilder*) clearRoleInClass;
@end

#define SRXProtoReadClassResponse_class_collection @"classCollection"
@interface SRXProtoReadClassResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * classCollectionArray;
}
@property (readonly, strong) NSArray * classCollection;
- (SRXDataClassInfo*)classCollectionAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoReadClassResponseBuilder*) builder;
+ (SRXProtoReadClassResponseBuilder*) builder;
+ (SRXProtoReadClassResponseBuilder*) builderWithPrototype:(SRXProtoReadClassResponse*) prototype;
- (SRXProtoReadClassResponseBuilder*) toBuilder;

+ (SRXProtoReadClassResponse*) parseFromData:(NSData*) data;
+ (SRXProtoReadClassResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoReadClassResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoReadClassResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoReadClassResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoReadClassResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoReadClassResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoReadClassResponse* resultSrxprotoReadClassResponse;
}

- (SRXProtoReadClassResponse*) defaultInstance;

- (SRXProtoReadClassResponseBuilder*) clear;
- (SRXProtoReadClassResponseBuilder*) clone;

- (SRXProtoReadClassResponse*) build;
- (SRXProtoReadClassResponse*) buildPartial;

- (SRXProtoReadClassResponseBuilder*) mergeFrom:(SRXProtoReadClassResponse*) other;
- (SRXProtoReadClassResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoReadClassResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)classCollection;
- (SRXDataClassInfo*)classCollectionAtIndex:(NSUInteger)index;
- (SRXProtoReadClassResponseBuilder *)addClassCollection:(SRXDataClassInfo*)value;
- (SRXProtoReadClassResponseBuilder *)setClassCollectionArray:(NSArray *)array;
- (SRXProtoReadClassResponseBuilder *)clearClassCollection;
@end

#define SRXProtoSearchClassRequest_latitude @"latitude"
#define SRXProtoSearchClassRequest_longtitude @"longtitude"
#define SRXProtoSearchClassRequest_radius_latitude @"radiusLatitude"
#define SRXProtoSearchClassRequest_radius_longtitude @"radiusLongtitude"
@interface SRXProtoSearchClassRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLatitude_:1;
  BOOL hasLongtitude_:1;
  BOOL hasRadiusLatitude_:1;
  BOOL hasRadiusLongtitude_:1;
  Float32 latitude;
  Float32 longtitude;
  Float32 radiusLatitude;
  Float32 radiusLongtitude;
}
- (BOOL) hasLatitude;
- (BOOL) hasLongtitude;
- (BOOL) hasRadiusLatitude;
- (BOOL) hasRadiusLongtitude;
@property (readonly) Float32 latitude;
@property (readonly) Float32 longtitude;
@property (readonly) Float32 radiusLatitude;
@property (readonly) Float32 radiusLongtitude;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoSearchClassRequestBuilder*) builder;
+ (SRXProtoSearchClassRequestBuilder*) builder;
+ (SRXProtoSearchClassRequestBuilder*) builderWithPrototype:(SRXProtoSearchClassRequest*) prototype;
- (SRXProtoSearchClassRequestBuilder*) toBuilder;

+ (SRXProtoSearchClassRequest*) parseFromData:(NSData*) data;
+ (SRXProtoSearchClassRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoSearchClassRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoSearchClassRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoSearchClassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoSearchClassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoSearchClassRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoSearchClassRequest* resultSrxprotoSearchClassRequest;
}

- (SRXProtoSearchClassRequest*) defaultInstance;

- (SRXProtoSearchClassRequestBuilder*) clear;
- (SRXProtoSearchClassRequestBuilder*) clone;

- (SRXProtoSearchClassRequest*) build;
- (SRXProtoSearchClassRequest*) buildPartial;

- (SRXProtoSearchClassRequestBuilder*) mergeFrom:(SRXProtoSearchClassRequest*) other;
- (SRXProtoSearchClassRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoSearchClassRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLatitude;
- (Float32) latitude;
- (SRXProtoSearchClassRequestBuilder*) setLatitude:(Float32) value;
- (SRXProtoSearchClassRequestBuilder*) clearLatitude;

- (BOOL) hasLongtitude;
- (Float32) longtitude;
- (SRXProtoSearchClassRequestBuilder*) setLongtitude:(Float32) value;
- (SRXProtoSearchClassRequestBuilder*) clearLongtitude;

- (BOOL) hasRadiusLatitude;
- (Float32) radiusLatitude;
- (SRXProtoSearchClassRequestBuilder*) setRadiusLatitude:(Float32) value;
- (SRXProtoSearchClassRequestBuilder*) clearRadiusLatitude;

- (BOOL) hasRadiusLongtitude;
- (Float32) radiusLongtitude;
- (SRXProtoSearchClassRequestBuilder*) setRadiusLongtitude:(Float32) value;
- (SRXProtoSearchClassRequestBuilder*) clearRadiusLongtitude;
@end

#define SRXProtoSearchClassResponse_class_collection @"classCollection"
@interface SRXProtoSearchClassResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * classCollectionArray;
}
@property (readonly, strong) NSArray * classCollection;
- (SRXDataClassInfo*)classCollectionAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoSearchClassResponseBuilder*) builder;
+ (SRXProtoSearchClassResponseBuilder*) builder;
+ (SRXProtoSearchClassResponseBuilder*) builderWithPrototype:(SRXProtoSearchClassResponse*) prototype;
- (SRXProtoSearchClassResponseBuilder*) toBuilder;

+ (SRXProtoSearchClassResponse*) parseFromData:(NSData*) data;
+ (SRXProtoSearchClassResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoSearchClassResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoSearchClassResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoSearchClassResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoSearchClassResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoSearchClassResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoSearchClassResponse* resultSrxprotoSearchClassResponse;
}

- (SRXProtoSearchClassResponse*) defaultInstance;

- (SRXProtoSearchClassResponseBuilder*) clear;
- (SRXProtoSearchClassResponseBuilder*) clone;

- (SRXProtoSearchClassResponse*) build;
- (SRXProtoSearchClassResponse*) buildPartial;

- (SRXProtoSearchClassResponseBuilder*) mergeFrom:(SRXProtoSearchClassResponse*) other;
- (SRXProtoSearchClassResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoSearchClassResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)classCollection;
- (SRXDataClassInfo*)classCollectionAtIndex:(NSUInteger)index;
- (SRXProtoSearchClassResponseBuilder *)addClassCollection:(SRXDataClassInfo*)value;
- (SRXProtoSearchClassResponseBuilder *)setClassCollectionArray:(NSArray *)array;
- (SRXProtoSearchClassResponseBuilder *)clearClassCollection;
@end

#define SRXProtoNativeLogInMessage_user_name @"userName"
#define SRXProtoNativeLogInMessage_password @"password"
@interface SRXProtoNativeLogInMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserName_:1;
  BOOL hasPassword_:1;
  NSString* userName;
  NSString* password;
}
- (BOOL) hasUserName;
- (BOOL) hasPassword;
@property (readonly, strong) NSString* userName;
@property (readonly, strong) NSString* password;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoNativeLogInMessageBuilder*) builder;
+ (SRXProtoNativeLogInMessageBuilder*) builder;
+ (SRXProtoNativeLogInMessageBuilder*) builderWithPrototype:(SRXProtoNativeLogInMessage*) prototype;
- (SRXProtoNativeLogInMessageBuilder*) toBuilder;

+ (SRXProtoNativeLogInMessage*) parseFromData:(NSData*) data;
+ (SRXProtoNativeLogInMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoNativeLogInMessage*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoNativeLogInMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoNativeLogInMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoNativeLogInMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoNativeLogInMessageBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoNativeLogInMessage* resultSrxprotoNativeLogInMessage;
}

- (SRXProtoNativeLogInMessage*) defaultInstance;

- (SRXProtoNativeLogInMessageBuilder*) clear;
- (SRXProtoNativeLogInMessageBuilder*) clone;

- (SRXProtoNativeLogInMessage*) build;
- (SRXProtoNativeLogInMessage*) buildPartial;

- (SRXProtoNativeLogInMessageBuilder*) mergeFrom:(SRXProtoNativeLogInMessage*) other;
- (SRXProtoNativeLogInMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoNativeLogInMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserName;
- (NSString*) userName;
- (SRXProtoNativeLogInMessageBuilder*) setUserName:(NSString*) value;
- (SRXProtoNativeLogInMessageBuilder*) clearUserName;

- (BOOL) hasPassword;
- (NSString*) password;
- (SRXProtoNativeLogInMessageBuilder*) setPassword:(NSString*) value;
- (SRXProtoNativeLogInMessageBuilder*) clearPassword;
@end

#define SRXProtoLogInRequest_log_in_method @"logInMethod"
#define SRXProtoLogInRequest_native_log_in @"nativeLogIn"
@interface SRXProtoLogInRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasNativeLogIn_:1;
  BOOL hasLogInMethod_:1;
  SRXProtoNativeLogInMessage* nativeLogIn;
  SRXProtoLogInMethodEnum logInMethod;
}
- (BOOL) hasLogInMethod;
- (BOOL) hasNativeLogIn;
@property (readonly) SRXProtoLogInMethodEnum logInMethod;
@property (readonly, strong) SRXProtoNativeLogInMessage* nativeLogIn;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoLogInRequestBuilder*) builder;
+ (SRXProtoLogInRequestBuilder*) builder;
+ (SRXProtoLogInRequestBuilder*) builderWithPrototype:(SRXProtoLogInRequest*) prototype;
- (SRXProtoLogInRequestBuilder*) toBuilder;

+ (SRXProtoLogInRequest*) parseFromData:(NSData*) data;
+ (SRXProtoLogInRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoLogInRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoLogInRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoLogInRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoLogInRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoLogInRequestBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoLogInRequest* resultSrxprotoLogInRequest;
}

- (SRXProtoLogInRequest*) defaultInstance;

- (SRXProtoLogInRequestBuilder*) clear;
- (SRXProtoLogInRequestBuilder*) clone;

- (SRXProtoLogInRequest*) build;
- (SRXProtoLogInRequest*) buildPartial;

- (SRXProtoLogInRequestBuilder*) mergeFrom:(SRXProtoLogInRequest*) other;
- (SRXProtoLogInRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoLogInRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLogInMethod;
- (SRXProtoLogInMethodEnum) logInMethod;
- (SRXProtoLogInRequestBuilder*) setLogInMethod:(SRXProtoLogInMethodEnum) value;
- (SRXProtoLogInRequestBuilder*) clearLogInMethod;

- (BOOL) hasNativeLogIn;
- (SRXProtoNativeLogInMessage*) nativeLogIn;
- (SRXProtoLogInRequestBuilder*) setNativeLogIn:(SRXProtoNativeLogInMessage*) value;
- (SRXProtoLogInRequestBuilder*) setNativeLogInBuilder:(SRXProtoNativeLogInMessageBuilder*) builderForValue;
- (SRXProtoLogInRequestBuilder*) mergeNativeLogIn:(SRXProtoNativeLogInMessage*) value;
- (SRXProtoLogInRequestBuilder*) clearNativeLogIn;
@end

#define SRXProtoLogInResponse_user @"user"
@interface SRXProtoLogInResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUser_:1;
  SRXDataUser* user;
}
- (BOOL) hasUser;
@property (readonly, strong) SRXDataUser* user;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXProtoLogInResponseBuilder*) builder;
+ (SRXProtoLogInResponseBuilder*) builder;
+ (SRXProtoLogInResponseBuilder*) builderWithPrototype:(SRXProtoLogInResponse*) prototype;
- (SRXProtoLogInResponseBuilder*) toBuilder;

+ (SRXProtoLogInResponse*) parseFromData:(NSData*) data;
+ (SRXProtoLogInResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoLogInResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SRXProtoLogInResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXProtoLogInResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXProtoLogInResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXProtoLogInResponseBuilder : PBGeneratedMessageBuilder {
@private
  SRXProtoLogInResponse* resultSrxprotoLogInResponse;
}

- (SRXProtoLogInResponse*) defaultInstance;

- (SRXProtoLogInResponseBuilder*) clear;
- (SRXProtoLogInResponseBuilder*) clone;

- (SRXProtoLogInResponse*) build;
- (SRXProtoLogInResponse*) buildPartial;

- (SRXProtoLogInResponseBuilder*) mergeFrom:(SRXProtoLogInResponse*) other;
- (SRXProtoLogInResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXProtoLogInResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUser;
- (SRXDataUser*) user;
- (SRXProtoLogInResponseBuilder*) setUser:(SRXDataUser*) value;
- (SRXProtoLogInResponseBuilder*) setUserBuilder:(SRXDataUserBuilder*) builderForValue;
- (SRXProtoLogInResponseBuilder*) mergeUser:(SRXDataUser*) value;
- (SRXProtoLogInResponseBuilder*) clearUser;
@end


// @@protoc_insertion_point(global_scope)
