// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class SRXDataLocation;
@class SRXDataLocationBuilder;


typedef NS_ENUM(SInt32, SRXDataCityEnum) {
  SRXDataCityEnumBeijing = 10,
  SRXDataCityEnumGuangzhou = 20,
  SRXDataCityEnumShanghai = 21,
  SRXDataCityEnumTianjin = 22,
  SRXDataCityEnumChongqin = 23,
  SRXDataCityEnumChangsha = 731,
};

BOOL SRXDataCityEnumIsValidValue(SRXDataCityEnum value);
NSString *NSStringFromSRXDataCityEnum(SRXDataCityEnum value);


@interface SrxdataLocationRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define SRXDataLocation_city @"city"
#define SRXDataLocation_street_name @"streetName"
#define SRXDataLocation_latitude @"latitude"
#define SRXDataLocation_longtitude @"longtitude"
@interface SRXDataLocation : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLatitude_:1;
  BOOL hasLongtitude_:1;
  BOOL hasStreetName_:1;
  BOOL hasCity_:1;
  Float32 latitude;
  Float32 longtitude;
  NSString* streetName;
  SRXDataCityEnum city;
}
- (BOOL) hasCity;
- (BOOL) hasStreetName;
- (BOOL) hasLatitude;
- (BOOL) hasLongtitude;
@property (readonly) SRXDataCityEnum city;
@property (readonly, strong) NSString* streetName;
@property (readonly) Float32 latitude;
@property (readonly) Float32 longtitude;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXDataLocationBuilder*) builder;
+ (SRXDataLocationBuilder*) builder;
+ (SRXDataLocationBuilder*) builderWithPrototype:(SRXDataLocation*) prototype;
- (SRXDataLocationBuilder*) toBuilder;

+ (SRXDataLocation*) parseFromData:(NSData*) data;
+ (SRXDataLocation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataLocation*) parseFromInputStream:(NSInputStream*) input;
+ (SRXDataLocation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataLocation*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXDataLocation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXDataLocationBuilder : PBGeneratedMessageBuilder {
@private
  SRXDataLocation* resultSrxdataLocation;
}

- (SRXDataLocation*) defaultInstance;

- (SRXDataLocationBuilder*) clear;
- (SRXDataLocationBuilder*) clone;

- (SRXDataLocation*) build;
- (SRXDataLocation*) buildPartial;

- (SRXDataLocationBuilder*) mergeFrom:(SRXDataLocation*) other;
- (SRXDataLocationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXDataLocationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCity;
- (SRXDataCityEnum) city;
- (SRXDataLocationBuilder*) setCity:(SRXDataCityEnum) value;
- (SRXDataLocationBuilder*) clearCity;

- (BOOL) hasStreetName;
- (NSString*) streetName;
- (SRXDataLocationBuilder*) setStreetName:(NSString*) value;
- (SRXDataLocationBuilder*) clearStreetName;

- (BOOL) hasLatitude;
- (Float32) latitude;
- (SRXDataLocationBuilder*) setLatitude:(Float32) value;
- (SRXDataLocationBuilder*) clearLatitude;

- (BOOL) hasLongtitude;
- (Float32) longtitude;
- (SRXDataLocationBuilder*) setLongtitude:(Float32) value;
- (SRXDataLocationBuilder*) clearLongtitude;
@end


// @@protoc_insertion_point(global_scope)
