// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "SRXDataLocation.pb.h"
#import "SRXDataImage.pb.h"
// @@protoc_insertion_point(imports)

@class SRXDataClass;
@class SRXDataClassBuilder;
@class SRXDataClassInfo;
@class SRXDataClassInfoBuilder;
@class SRXDataClassTime;
@class SRXDataClassTimeBuilder;
@class SRXDataClassTypeEnum;
@class SRXDataClassTypeEnumBuilder;
@class SRXDataImage;
@class SRXDataImageBuilder;
@class SRXDataImageRef;
@class SRXDataImageRefBuilder;
@class SRXDataImageServerTypeEnum;
@class SRXDataImageServerTypeEnumBuilder;
@class SRXDataLocation;
@class SRXDataLocationBuilder;


typedef NS_ENUM(SInt32, SRXDataClassTypeEnumSRXDataClassType) {
  SRXDataClassTypeEnumSRXDataClassTypeUnknown = 0,
  SRXDataClassTypeEnumSRXDataClassTypeYuwen = 1,
  SRXDataClassTypeEnumSRXDataClassTypeShuxue = 2,
  SRXDataClassTypeEnumSRXDataClassTypeYingyu = 3,
  SRXDataClassTypeEnumSRXDataClassTypeHechang = 101,
  SRXDataClassTypeEnumSRXDataClassTypeWudao = 102,
  SRXDataClassTypeEnumSRXDataClassTypeGangqin = 103,
  SRXDataClassTypeEnumSRXDataClassTypeWeiqi = 201,
  SRXDataClassTypeEnumSRXDataClassTypeZhongguoxiangqi = 202,
  SRXDataClassTypeEnumSRXDataClassTypeGuojixiangqi = 203,
  SRXDataClassTypeEnumSRXDataClassTypeShufa = 301,
  SRXDataClassTypeEnumSRXDataClassTypeHuihua = 401,
  SRXDataClassTypeEnumSRXDataClassTypeWushu = 501,
};

BOOL SRXDataClassTypeEnumSRXDataClassTypeIsValidValue(SRXDataClassTypeEnumSRXDataClassType value);
NSString *NSStringFromSRXDataClassTypeEnumSRXDataClassType(SRXDataClassTypeEnumSRXDataClassType value);


@interface SrxdataClassRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface SRXDataClassTypeEnum : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXDataClassTypeEnumBuilder*) builder;
+ (SRXDataClassTypeEnumBuilder*) builder;
+ (SRXDataClassTypeEnumBuilder*) builderWithPrototype:(SRXDataClassTypeEnum*) prototype;
- (SRXDataClassTypeEnumBuilder*) toBuilder;

+ (SRXDataClassTypeEnum*) parseFromData:(NSData*) data;
+ (SRXDataClassTypeEnum*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataClassTypeEnum*) parseFromInputStream:(NSInputStream*) input;
+ (SRXDataClassTypeEnum*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataClassTypeEnum*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXDataClassTypeEnum*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXDataClassTypeEnumBuilder : PBGeneratedMessageBuilder {
@private
  SRXDataClassTypeEnum* resultSrxdataClassTypeEnum;
}

- (SRXDataClassTypeEnum*) defaultInstance;

- (SRXDataClassTypeEnumBuilder*) clear;
- (SRXDataClassTypeEnumBuilder*) clone;

- (SRXDataClassTypeEnum*) build;
- (SRXDataClassTypeEnum*) buildPartial;

- (SRXDataClassTypeEnumBuilder*) mergeFrom:(SRXDataClassTypeEnum*) other;
- (SRXDataClassTypeEnumBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXDataClassTypeEnumBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXDataClassTime : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXDataClassTimeBuilder*) builder;
+ (SRXDataClassTimeBuilder*) builder;
+ (SRXDataClassTimeBuilder*) builderWithPrototype:(SRXDataClassTime*) prototype;
- (SRXDataClassTimeBuilder*) toBuilder;

+ (SRXDataClassTime*) parseFromData:(NSData*) data;
+ (SRXDataClassTime*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataClassTime*) parseFromInputStream:(NSInputStream*) input;
+ (SRXDataClassTime*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataClassTime*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXDataClassTime*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXDataClassTimeBuilder : PBGeneratedMessageBuilder {
@private
  SRXDataClassTime* resultSrxdataClassTime;
}

- (SRXDataClassTime*) defaultInstance;

- (SRXDataClassTimeBuilder*) clear;
- (SRXDataClassTimeBuilder*) clone;

- (SRXDataClassTime*) build;
- (SRXDataClassTime*) buildPartial;

- (SRXDataClassTimeBuilder*) mergeFrom:(SRXDataClassTime*) other;
- (SRXDataClassTimeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXDataClassTimeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define SRXDataClassInfo_teacher_name @"teacherName"
#define SRXDataClassInfo_class_type @"classType"
#define SRXDataClassInfo_location @"location"
#define SRXDataClassInfo_class_time @"classTime"
#define SRXDataClassInfo_number_of_classes @"numberOfClasses"
#define SRXDataClassInfo_tuition_fee_in_yuan @"tuitionFeeInYuan"
#define SRXDataClassInfo_summary @"summary"
#define SRXDataClassInfo_image_ref @"imageRef"
@interface SRXDataClassInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasNumberOfClasses_:1;
  BOOL hasTuitionFeeInYuan_:1;
  BOOL hasTeacherName_:1;
  BOOL hasSummary_:1;
  BOOL hasLocation_:1;
  BOOL hasClassTime_:1;
  BOOL hasClassType_:1;
  SInt32 numberOfClasses;
  SInt32 tuitionFeeInYuan;
  NSString* teacherName;
  NSString* summary;
  SRXDataLocation* location;
  SRXDataClassTime* classTime;
  SRXDataClassTypeEnumSRXDataClassType classType;
  NSMutableArray * imageRefArray;
}
- (BOOL) hasTeacherName;
- (BOOL) hasClassType;
- (BOOL) hasLocation;
- (BOOL) hasClassTime;
- (BOOL) hasNumberOfClasses;
- (BOOL) hasTuitionFeeInYuan;
- (BOOL) hasSummary;
@property (readonly, strong) NSString* teacherName;
@property (readonly) SRXDataClassTypeEnumSRXDataClassType classType;
@property (readonly, strong) SRXDataLocation* location;
@property (readonly, strong) SRXDataClassTime* classTime;
@property (readonly) SInt32 numberOfClasses;
@property (readonly) SInt32 tuitionFeeInYuan;
@property (readonly, strong) NSString* summary;
@property (readonly, strong) NSArray * imageRef;
- (SRXDataImageRef*)imageRefAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXDataClassInfoBuilder*) builder;
+ (SRXDataClassInfoBuilder*) builder;
+ (SRXDataClassInfoBuilder*) builderWithPrototype:(SRXDataClassInfo*) prototype;
- (SRXDataClassInfoBuilder*) toBuilder;

+ (SRXDataClassInfo*) parseFromData:(NSData*) data;
+ (SRXDataClassInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataClassInfo*) parseFromInputStream:(NSInputStream*) input;
+ (SRXDataClassInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataClassInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXDataClassInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXDataClassInfoBuilder : PBGeneratedMessageBuilder {
@private
  SRXDataClassInfo* resultSrxdataClassInfo;
}

- (SRXDataClassInfo*) defaultInstance;

- (SRXDataClassInfoBuilder*) clear;
- (SRXDataClassInfoBuilder*) clone;

- (SRXDataClassInfo*) build;
- (SRXDataClassInfo*) buildPartial;

- (SRXDataClassInfoBuilder*) mergeFrom:(SRXDataClassInfo*) other;
- (SRXDataClassInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXDataClassInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTeacherName;
- (NSString*) teacherName;
- (SRXDataClassInfoBuilder*) setTeacherName:(NSString*) value;
- (SRXDataClassInfoBuilder*) clearTeacherName;

- (BOOL) hasClassType;
- (SRXDataClassTypeEnumSRXDataClassType) classType;
- (SRXDataClassInfoBuilder*) setClassType:(SRXDataClassTypeEnumSRXDataClassType) value;
- (SRXDataClassInfoBuilder*) clearClassType;

- (BOOL) hasLocation;
- (SRXDataLocation*) location;
- (SRXDataClassInfoBuilder*) setLocation:(SRXDataLocation*) value;
- (SRXDataClassInfoBuilder*) setLocationBuilder:(SRXDataLocationBuilder*) builderForValue;
- (SRXDataClassInfoBuilder*) mergeLocation:(SRXDataLocation*) value;
- (SRXDataClassInfoBuilder*) clearLocation;

- (BOOL) hasClassTime;
- (SRXDataClassTime*) classTime;
- (SRXDataClassInfoBuilder*) setClassTime:(SRXDataClassTime*) value;
- (SRXDataClassInfoBuilder*) setClassTimeBuilder:(SRXDataClassTimeBuilder*) builderForValue;
- (SRXDataClassInfoBuilder*) mergeClassTime:(SRXDataClassTime*) value;
- (SRXDataClassInfoBuilder*) clearClassTime;

- (BOOL) hasNumberOfClasses;
- (SInt32) numberOfClasses;
- (SRXDataClassInfoBuilder*) setNumberOfClasses:(SInt32) value;
- (SRXDataClassInfoBuilder*) clearNumberOfClasses;

- (BOOL) hasTuitionFeeInYuan;
- (SInt32) tuitionFeeInYuan;
- (SRXDataClassInfoBuilder*) setTuitionFeeInYuan:(SInt32) value;
- (SRXDataClassInfoBuilder*) clearTuitionFeeInYuan;

- (BOOL) hasSummary;
- (NSString*) summary;
- (SRXDataClassInfoBuilder*) setSummary:(NSString*) value;
- (SRXDataClassInfoBuilder*) clearSummary;

- (NSMutableArray *)imageRef;
- (SRXDataImageRef*)imageRefAtIndex:(NSUInteger)index;
- (SRXDataClassInfoBuilder *)addImageRef:(SRXDataImageRef*)value;
- (SRXDataClassInfoBuilder *)setImageRefArray:(NSArray *)array;
- (SRXDataClassInfoBuilder *)clearImageRef;
@end

#define SRXDataClass_id @"id"
#define SRXDataClass_class_info @"classInfo"
@interface SRXDataClass : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasClassInfo_:1;
  SInt64 id;
  SRXDataClassInfo* classInfo;
}
- (BOOL) hasId;
- (BOOL) hasClassInfo;
@property (readonly) SInt64 id;
@property (readonly, strong) SRXDataClassInfo* classInfo;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXDataClassBuilder*) builder;
+ (SRXDataClassBuilder*) builder;
+ (SRXDataClassBuilder*) builderWithPrototype:(SRXDataClass*) prototype;
- (SRXDataClassBuilder*) toBuilder;

+ (SRXDataClass*) parseFromData:(NSData*) data;
+ (SRXDataClass*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataClass*) parseFromInputStream:(NSInputStream*) input;
+ (SRXDataClass*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataClass*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXDataClass*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXDataClassBuilder : PBGeneratedMessageBuilder {
@private
  SRXDataClass* resultSrxdataClass;
}

- (SRXDataClass*) defaultInstance;

- (SRXDataClassBuilder*) clear;
- (SRXDataClassBuilder*) clone;

- (SRXDataClass*) build;
- (SRXDataClass*) buildPartial;

- (SRXDataClassBuilder*) mergeFrom:(SRXDataClass*) other;
- (SRXDataClassBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXDataClassBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (SRXDataClassBuilder*) setId:(SInt64) value;
- (SRXDataClassBuilder*) clearId;

- (BOOL) hasClassInfo;
- (SRXDataClassInfo*) classInfo;
- (SRXDataClassBuilder*) setClassInfo:(SRXDataClassInfo*) value;
- (SRXDataClassBuilder*) setClassInfoBuilder:(SRXDataClassInfoBuilder*) builderForValue;
- (SRXDataClassBuilder*) mergeClassInfo:(SRXDataClassInfo*) value;
- (SRXDataClassBuilder*) clearClassInfo;
@end


// @@protoc_insertion_point(global_scope)
