// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "SRXDataSchool.pb.h"
// @@protoc_insertion_point(imports)

@implementation SrxdataSchoolRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [SrxdataSchoolRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [SrxdataLocationRoot registerAllExtensions:registry];
    [SrxdataImageRoot registerAllExtensions:registry];
    [SrxdataTeacherRoot registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface SRXDataSchoolInfo ()
@property (strong) SRXDataLocation* location;
@property (strong) NSString* name;
@property (strong) NSString* pb_description;
@property (strong) NSMutableArray * imageRefArray;
@property (strong) NSMutableArray * teacherArray;
@end

@implementation SRXDataSchoolInfo

- (BOOL) hasLocation {
  return !!hasLocation_;
}
- (void) setHasLocation:(BOOL) _value_ {
  hasLocation_ = !!_value_;
}
@synthesize location;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) _value_ {
  hasName_ = !!_value_;
}
@synthesize name;
- (BOOL) hasDescription {
  return !!hasDescription_;
}
- (void) setHasDescription:(BOOL) _value_ {
  hasDescription_ = !!_value_;
}
@synthesize pb_description;
@synthesize imageRefArray;
@dynamic imageRef;
@synthesize teacherArray;
@dynamic teacher;
- (instancetype) init {
  if ((self = [super init])) {
    self.location = [SRXDataLocation defaultInstance];
    self.name = @"";
    self.pb_description = @"";
  }
  return self;
}
static SRXDataSchoolInfo* defaultSRXDataSchoolInfoInstance = nil;
+ (void) initialize {
  if (self == [SRXDataSchoolInfo class]) {
    defaultSRXDataSchoolInfoInstance = [[SRXDataSchoolInfo alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultSRXDataSchoolInfoInstance;
}
- (instancetype) defaultInstance {
  return defaultSRXDataSchoolInfoInstance;
}
- (NSArray *)imageRef {
  return imageRefArray;
}
- (SRXDataImageRef*)imageRefAtIndex:(NSUInteger)index {
  return [imageRefArray objectAtIndex:index];
}
- (NSArray *)teacher {
  return teacherArray;
}
- (SRXDataTeacher*)teacherAtIndex:(NSUInteger)index {
  return [teacherArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasLocation) {
    [output writeMessage:1 value:self.location];
  }
  if (self.hasName) {
    [output writeString:2 value:self.name];
  }
  if (self.hasDescription) {
    [output writeString:3 value:self.pb_description];
  }
  [self.imageRefArray enumerateObjectsUsingBlock:^(SRXDataImageRef *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:4 value:element];
  }];
  [self.teacherArray enumerateObjectsUsingBlock:^(SRXDataTeacher *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:5 value:element];
  }];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasLocation) {
    size_ += computeMessageSize(1, self.location);
  }
  if (self.hasName) {
    size_ += computeStringSize(2, self.name);
  }
  if (self.hasDescription) {
    size_ += computeStringSize(3, self.pb_description);
  }
  [self.imageRefArray enumerateObjectsUsingBlock:^(SRXDataImageRef *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(4, element);
  }];
  [self.teacherArray enumerateObjectsUsingBlock:^(SRXDataTeacher *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(5, element);
  }];
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (SRXDataSchoolInfo*) parseFromData:(NSData*) data {
  return (SRXDataSchoolInfo*)[[[SRXDataSchoolInfo builder] mergeFromData:data] build];
}
+ (SRXDataSchoolInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SRXDataSchoolInfo*)[[[SRXDataSchoolInfo builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (SRXDataSchoolInfo*) parseFromInputStream:(NSInputStream*) input {
  return (SRXDataSchoolInfo*)[[[SRXDataSchoolInfo builder] mergeFromInputStream:input] build];
}
+ (SRXDataSchoolInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SRXDataSchoolInfo*)[[[SRXDataSchoolInfo builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SRXDataSchoolInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (SRXDataSchoolInfo*)[[[SRXDataSchoolInfo builder] mergeFromCodedInputStream:input] build];
}
+ (SRXDataSchoolInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SRXDataSchoolInfo*)[[[SRXDataSchoolInfo builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SRXDataSchoolInfoBuilder*) builder {
  return [[SRXDataSchoolInfoBuilder alloc] init];
}
+ (SRXDataSchoolInfoBuilder*) builderWithPrototype:(SRXDataSchoolInfo*) prototype {
  return [[SRXDataSchoolInfo builder] mergeFrom:prototype];
}
- (SRXDataSchoolInfoBuilder*) builder {
  return [SRXDataSchoolInfo builder];
}
- (SRXDataSchoolInfoBuilder*) toBuilder {
  return [SRXDataSchoolInfo builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasLocation) {
    [output appendFormat:@"%@%@ {\n", indent, @"location"];
    [self.location writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"name", self.name];
  }
  if (self.hasDescription) {
    [output appendFormat:@"%@%@: %@\n", indent, @"pb_description", self.pb_description];
  }
  [self.imageRefArray enumerateObjectsUsingBlock:^(SRXDataImageRef *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"imageRef"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.teacherArray enumerateObjectsUsingBlock:^(SRXDataTeacher *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"teacher"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasLocation) {
   NSMutableDictionary *messageDictionary = [NSMutableDictionary dictionary]; 
   [self.location storeInDictionary:messageDictionary];
   [dictionary setObject:[NSDictionary dictionaryWithDictionary:messageDictionary] forKey:@"location"];
  }
  if (self.hasName) {
    [dictionary setObject: self.name forKey: @"name"];
  }
  if (self.hasDescription) {
    [dictionary setObject: self.pb_description forKey: @"pb_description"];
  }
  for (SRXDataImageRef* element in self.imageRefArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"imageRef"];
  }
  for (SRXDataTeacher* element in self.teacherArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"teacher"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[SRXDataSchoolInfo class]]) {
    return NO;
  }
  SRXDataSchoolInfo *otherMessage = other;
  return
      self.hasLocation == otherMessage.hasLocation &&
      (!self.hasLocation || [self.location isEqual:otherMessage.location]) &&
      self.hasName == otherMessage.hasName &&
      (!self.hasName || [self.name isEqual:otherMessage.name]) &&
      self.hasDescription == otherMessage.hasDescription &&
      (!self.hasDescription || [self.pb_description isEqual:otherMessage.pb_description]) &&
      [self.imageRefArray isEqualToArray:otherMessage.imageRefArray] &&
      [self.teacherArray isEqualToArray:otherMessage.teacherArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasLocation) {
    hashCode = hashCode * 31 + [self.location hash];
  }
  if (self.hasName) {
    hashCode = hashCode * 31 + [self.name hash];
  }
  if (self.hasDescription) {
    hashCode = hashCode * 31 + [self.pb_description hash];
  }
  [self.imageRefArray enumerateObjectsUsingBlock:^(SRXDataImageRef *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  [self.teacherArray enumerateObjectsUsingBlock:^(SRXDataTeacher *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface SRXDataSchoolInfoBuilder()
@property (strong) SRXDataSchoolInfo* resultSrxdataSchoolInfo;
@end

@implementation SRXDataSchoolInfoBuilder
@synthesize resultSrxdataSchoolInfo;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultSrxdataSchoolInfo = [[SRXDataSchoolInfo alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultSrxdataSchoolInfo;
}
- (SRXDataSchoolInfoBuilder*) clear {
  self.resultSrxdataSchoolInfo = [[SRXDataSchoolInfo alloc] init];
  return self;
}
- (SRXDataSchoolInfoBuilder*) clone {
  return [SRXDataSchoolInfo builderWithPrototype:resultSrxdataSchoolInfo];
}
- (SRXDataSchoolInfo*) defaultInstance {
  return [SRXDataSchoolInfo defaultInstance];
}
- (SRXDataSchoolInfo*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (SRXDataSchoolInfo*) buildPartial {
  SRXDataSchoolInfo* returnMe = resultSrxdataSchoolInfo;
  self.resultSrxdataSchoolInfo = nil;
  return returnMe;
}
- (SRXDataSchoolInfoBuilder*) mergeFrom:(SRXDataSchoolInfo*) other {
  if (other == [SRXDataSchoolInfo defaultInstance]) {
    return self;
  }
  if (other.hasLocation) {
    [self mergeLocation:other.location];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasDescription) {
    [self setDescription:other.pb_description];
  }
  if (other.imageRefArray.count > 0) {
    if (resultSrxdataSchoolInfo.imageRefArray == nil) {
      resultSrxdataSchoolInfo.imageRefArray = [[NSMutableArray alloc] initWithArray:other.imageRefArray];
    } else {
      [resultSrxdataSchoolInfo.imageRefArray addObjectsFromArray:other.imageRefArray];
    }
  }
  if (other.teacherArray.count > 0) {
    if (resultSrxdataSchoolInfo.teacherArray == nil) {
      resultSrxdataSchoolInfo.teacherArray = [[NSMutableArray alloc] initWithArray:other.teacherArray];
    } else {
      [resultSrxdataSchoolInfo.teacherArray addObjectsFromArray:other.teacherArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (SRXDataSchoolInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (SRXDataSchoolInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        SRXDataLocationBuilder* subBuilder = [SRXDataLocation builder];
        if (self.hasLocation) {
          [subBuilder mergeFrom:self.location];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setLocation:[subBuilder buildPartial]];
        break;
      }
      case 18: {
        [self setName:[input readString]];
        break;
      }
      case 26: {
        [self setDescription:[input readString]];
        break;
      }
      case 34: {
        SRXDataImageRefBuilder* subBuilder = [SRXDataImageRef builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addImageRef:[subBuilder buildPartial]];
        break;
      }
      case 42: {
        SRXDataTeacherBuilder* subBuilder = [SRXDataTeacher builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addTeacher:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasLocation {
  return resultSrxdataSchoolInfo.hasLocation;
}
- (SRXDataLocation*) location {
  return resultSrxdataSchoolInfo.location;
}
- (SRXDataSchoolInfoBuilder*) setLocation:(SRXDataLocation*) value {
  resultSrxdataSchoolInfo.hasLocation = YES;
  resultSrxdataSchoolInfo.location = value;
  return self;
}
- (SRXDataSchoolInfoBuilder*) setLocationBuilder:(SRXDataLocationBuilder*) builderForValue {
  return [self setLocation:[builderForValue build]];
}
- (SRXDataSchoolInfoBuilder*) mergeLocation:(SRXDataLocation*) value {
  if (resultSrxdataSchoolInfo.hasLocation &&
      resultSrxdataSchoolInfo.location != [SRXDataLocation defaultInstance]) {
    resultSrxdataSchoolInfo.location =
      [[[SRXDataLocation builderWithPrototype:resultSrxdataSchoolInfo.location] mergeFrom:value] buildPartial];
  } else {
    resultSrxdataSchoolInfo.location = value;
  }
  resultSrxdataSchoolInfo.hasLocation = YES;
  return self;
}
- (SRXDataSchoolInfoBuilder*) clearLocation {
  resultSrxdataSchoolInfo.hasLocation = NO;
  resultSrxdataSchoolInfo.location = [SRXDataLocation defaultInstance];
  return self;
}
- (BOOL) hasName {
  return resultSrxdataSchoolInfo.hasName;
}
- (NSString*) name {
  return resultSrxdataSchoolInfo.name;
}
- (SRXDataSchoolInfoBuilder*) setName:(NSString*) value {
  resultSrxdataSchoolInfo.hasName = YES;
  resultSrxdataSchoolInfo.name = value;
  return self;
}
- (SRXDataSchoolInfoBuilder*) clearName {
  resultSrxdataSchoolInfo.hasName = NO;
  resultSrxdataSchoolInfo.name = @"";
  return self;
}
- (BOOL) hasDescription {
  return resultSrxdataSchoolInfo.hasDescription;
}
- (NSString*) pb_description {
  return resultSrxdataSchoolInfo.pb_description;
}
- (SRXDataSchoolInfoBuilder*) setDescription:(NSString*) value {
  resultSrxdataSchoolInfo.hasDescription = YES;
  resultSrxdataSchoolInfo.pb_description = value;
  return self;
}
- (SRXDataSchoolInfoBuilder*) clearDescription {
  resultSrxdataSchoolInfo.hasDescription = NO;
  resultSrxdataSchoolInfo.pb_description = @"";
  return self;
}
- (NSMutableArray *)imageRef {
  return resultSrxdataSchoolInfo.imageRefArray;
}
- (SRXDataImageRef*)imageRefAtIndex:(NSUInteger)index {
  return [resultSrxdataSchoolInfo imageRefAtIndex:index];
}
- (SRXDataSchoolInfoBuilder *)addImageRef:(SRXDataImageRef*)value {
  if (resultSrxdataSchoolInfo.imageRefArray == nil) {
    resultSrxdataSchoolInfo.imageRefArray = [[NSMutableArray alloc]init];
  }
  [resultSrxdataSchoolInfo.imageRefArray addObject:value];
  return self;
}
- (SRXDataSchoolInfoBuilder *)setImageRefArray:(NSArray *)array {
  resultSrxdataSchoolInfo.imageRefArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (SRXDataSchoolInfoBuilder *)clearImageRef {
  resultSrxdataSchoolInfo.imageRefArray = nil;
  return self;
}
- (NSMutableArray *)teacher {
  return resultSrxdataSchoolInfo.teacherArray;
}
- (SRXDataTeacher*)teacherAtIndex:(NSUInteger)index {
  return [resultSrxdataSchoolInfo teacherAtIndex:index];
}
- (SRXDataSchoolInfoBuilder *)addTeacher:(SRXDataTeacher*)value {
  if (resultSrxdataSchoolInfo.teacherArray == nil) {
    resultSrxdataSchoolInfo.teacherArray = [[NSMutableArray alloc]init];
  }
  [resultSrxdataSchoolInfo.teacherArray addObject:value];
  return self;
}
- (SRXDataSchoolInfoBuilder *)setTeacherArray:(NSArray *)array {
  resultSrxdataSchoolInfo.teacherArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (SRXDataSchoolInfoBuilder *)clearTeacher {
  resultSrxdataSchoolInfo.teacherArray = nil;
  return self;
}
@end

@interface SRXDataSchool ()
@property (strong) NSString* id;
@property (strong) SRXDataSchoolInfo* info;
@end

@implementation SRXDataSchool

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value_ {
  hasId_ = !!_value_;
}
@synthesize id;
- (BOOL) hasInfo {
  return !!hasInfo_;
}
- (void) setHasInfo:(BOOL) _value_ {
  hasInfo_ = !!_value_;
}
@synthesize info;
- (instancetype) init {
  if ((self = [super init])) {
    self.id = @"";
    self.info = [SRXDataSchoolInfo defaultInstance];
  }
  return self;
}
static SRXDataSchool* defaultSRXDataSchoolInstance = nil;
+ (void) initialize {
  if (self == [SRXDataSchool class]) {
    defaultSRXDataSchoolInstance = [[SRXDataSchool alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultSRXDataSchoolInstance;
}
- (instancetype) defaultInstance {
  return defaultSRXDataSchoolInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasInfo) {
    [output writeMessage:2 value:self.info];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasId) {
    size_ += computeStringSize(1, self.id);
  }
  if (self.hasInfo) {
    size_ += computeMessageSize(2, self.info);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (SRXDataSchool*) parseFromData:(NSData*) data {
  return (SRXDataSchool*)[[[SRXDataSchool builder] mergeFromData:data] build];
}
+ (SRXDataSchool*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SRXDataSchool*)[[[SRXDataSchool builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (SRXDataSchool*) parseFromInputStream:(NSInputStream*) input {
  return (SRXDataSchool*)[[[SRXDataSchool builder] mergeFromInputStream:input] build];
}
+ (SRXDataSchool*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SRXDataSchool*)[[[SRXDataSchool builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SRXDataSchool*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (SRXDataSchool*)[[[SRXDataSchool builder] mergeFromCodedInputStream:input] build];
}
+ (SRXDataSchool*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SRXDataSchool*)[[[SRXDataSchool builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SRXDataSchoolBuilder*) builder {
  return [[SRXDataSchoolBuilder alloc] init];
}
+ (SRXDataSchoolBuilder*) builderWithPrototype:(SRXDataSchool*) prototype {
  return [[SRXDataSchool builder] mergeFrom:prototype];
}
- (SRXDataSchoolBuilder*) builder {
  return [SRXDataSchool builder];
}
- (SRXDataSchoolBuilder*) toBuilder {
  return [SRXDataSchool builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", self.id];
  }
  if (self.hasInfo) {
    [output appendFormat:@"%@%@ {\n", indent, @"info"];
    [self.info writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasId) {
    [dictionary setObject: self.id forKey: @"id"];
  }
  if (self.hasInfo) {
   NSMutableDictionary *messageDictionary = [NSMutableDictionary dictionary]; 
   [self.info storeInDictionary:messageDictionary];
   [dictionary setObject:[NSDictionary dictionaryWithDictionary:messageDictionary] forKey:@"info"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[SRXDataSchool class]]) {
    return NO;
  }
  SRXDataSchool *otherMessage = other;
  return
      self.hasId == otherMessage.hasId &&
      (!self.hasId || [self.id isEqual:otherMessage.id]) &&
      self.hasInfo == otherMessage.hasInfo &&
      (!self.hasInfo || [self.info isEqual:otherMessage.info]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasId) {
    hashCode = hashCode * 31 + [self.id hash];
  }
  if (self.hasInfo) {
    hashCode = hashCode * 31 + [self.info hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface SRXDataSchoolBuilder()
@property (strong) SRXDataSchool* resultSrxdataSchool;
@end

@implementation SRXDataSchoolBuilder
@synthesize resultSrxdataSchool;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultSrxdataSchool = [[SRXDataSchool alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultSrxdataSchool;
}
- (SRXDataSchoolBuilder*) clear {
  self.resultSrxdataSchool = [[SRXDataSchool alloc] init];
  return self;
}
- (SRXDataSchoolBuilder*) clone {
  return [SRXDataSchool builderWithPrototype:resultSrxdataSchool];
}
- (SRXDataSchool*) defaultInstance {
  return [SRXDataSchool defaultInstance];
}
- (SRXDataSchool*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (SRXDataSchool*) buildPartial {
  SRXDataSchool* returnMe = resultSrxdataSchool;
  self.resultSrxdataSchool = nil;
  return returnMe;
}
- (SRXDataSchoolBuilder*) mergeFrom:(SRXDataSchool*) other {
  if (other == [SRXDataSchool defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasInfo) {
    [self mergeInfo:other.info];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (SRXDataSchoolBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (SRXDataSchoolBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 18: {
        SRXDataSchoolInfoBuilder* subBuilder = [SRXDataSchoolInfo builder];
        if (self.hasInfo) {
          [subBuilder mergeFrom:self.info];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setInfo:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return resultSrxdataSchool.hasId;
}
- (NSString*) id {
  return resultSrxdataSchool.id;
}
- (SRXDataSchoolBuilder*) setId:(NSString*) value {
  resultSrxdataSchool.hasId = YES;
  resultSrxdataSchool.id = value;
  return self;
}
- (SRXDataSchoolBuilder*) clearId {
  resultSrxdataSchool.hasId = NO;
  resultSrxdataSchool.id = @"";
  return self;
}
- (BOOL) hasInfo {
  return resultSrxdataSchool.hasInfo;
}
- (SRXDataSchoolInfo*) info {
  return resultSrxdataSchool.info;
}
- (SRXDataSchoolBuilder*) setInfo:(SRXDataSchoolInfo*) value {
  resultSrxdataSchool.hasInfo = YES;
  resultSrxdataSchool.info = value;
  return self;
}
- (SRXDataSchoolBuilder*) setInfoBuilder:(SRXDataSchoolInfoBuilder*) builderForValue {
  return [self setInfo:[builderForValue build]];
}
- (SRXDataSchoolBuilder*) mergeInfo:(SRXDataSchoolInfo*) value {
  if (resultSrxdataSchool.hasInfo &&
      resultSrxdataSchool.info != [SRXDataSchoolInfo defaultInstance]) {
    resultSrxdataSchool.info =
      [[[SRXDataSchoolInfo builderWithPrototype:resultSrxdataSchool.info] mergeFrom:value] buildPartial];
  } else {
    resultSrxdataSchool.info = value;
  }
  resultSrxdataSchool.hasInfo = YES;
  return self;
}
- (SRXDataSchoolBuilder*) clearInfo {
  resultSrxdataSchool.hasInfo = NO;
  resultSrxdataSchool.info = [SRXDataSchoolInfo defaultInstance];
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
