// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class SRXDataPersonName;
@class SRXDataPersonNameBuilder;



@interface SrxdataPersonNameRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define SRXDataPersonName_family_name @"familyName"
#define SRXDataPersonName_given_name @"givenName"
@interface SRXDataPersonName : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFamilyName_:1;
  BOOL hasGivenName_:1;
  NSString* familyName;
  NSString* givenName;
}
- (BOOL) hasFamilyName;
- (BOOL) hasGivenName;
@property (readonly, strong) NSString* familyName;
@property (readonly, strong) NSString* givenName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SRXDataPersonNameBuilder*) builder;
+ (SRXDataPersonNameBuilder*) builder;
+ (SRXDataPersonNameBuilder*) builderWithPrototype:(SRXDataPersonName*) prototype;
- (SRXDataPersonNameBuilder*) toBuilder;

+ (SRXDataPersonName*) parseFromData:(NSData*) data;
+ (SRXDataPersonName*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataPersonName*) parseFromInputStream:(NSInputStream*) input;
+ (SRXDataPersonName*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SRXDataPersonName*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SRXDataPersonName*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SRXDataPersonNameBuilder : PBGeneratedMessageBuilder {
@private
  SRXDataPersonName* resultSrxdataPersonName;
}

- (SRXDataPersonName*) defaultInstance;

- (SRXDataPersonNameBuilder*) clear;
- (SRXDataPersonNameBuilder*) clone;

- (SRXDataPersonName*) build;
- (SRXDataPersonName*) buildPartial;

- (SRXDataPersonNameBuilder*) mergeFrom:(SRXDataPersonName*) other;
- (SRXDataPersonNameBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SRXDataPersonNameBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFamilyName;
- (NSString*) familyName;
- (SRXDataPersonNameBuilder*) setFamilyName:(NSString*) value;
- (SRXDataPersonNameBuilder*) clearFamilyName;

- (BOOL) hasGivenName;
- (NSString*) givenName;
- (SRXDataPersonNameBuilder*) setGivenName:(NSString*) value;
- (SRXDataPersonNameBuilder*) clearGivenName;
@end


// @@protoc_insertion_point(global_scope)
